<?php
/**
 * SkuStocksApi
 * PHP version 7.4
 *
 * @category Class
 * @package  com\jd\openapi\apiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */


/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace com\jd\openapi\apiClient\sp\product\v0\api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use com\jd\openapi\apiClient\ApiException;
use com\jd\openapi\apiClient\Configuration;
use com\jd\openapi\apiClient\HeaderSelector;
use com\jd\openapi\apiClient\ObjectSerializer;
use com\jd\openapi\apiClient\SignatureCalculator;
/**
 * SkuStocksApi Class Doc Comment
 *
 * @category Class
 * @package  com\jd\openapi\apiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SkuStocksApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'batchPutSkuStocks' => [
            'application/json',
                ],
        'listSkuStocks' => [
            'application/json',
                ],
    ];

    /**
     * @param Configuration config
     */
    public function __construct(
        $config
    ) {
        $this->client = new Client();
        $this->config = $config;
        $this->headerSelector = new HeaderSelector();
        $this->hostIndex = 0;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation batchPutSkuStocks
     *
     * @param  \com\jd\openapi\apiClient\sp\product\v0\model\BatchPutSkuStocksRequest $batch_put_sku_stocks_request batch_put_sku_stocks_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['batchPutSkuStocks'] to see the possible values for this operation
     *
     * @throws \com\jd\openapi\apiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \com\jd\openapi\apiClient\sp\product\v0\model\BatchPutSkuStocksResponse
     */
    public function batchPutSkuStocks($batch_put_sku_stocks_request, string $contentType = self::contentTypes['batchPutSkuStocks'][0])
    {
        list($response) = $this->batchPutSkuStocksWithHttpInfo($batch_put_sku_stocks_request, $contentType);
        return $response;
    }

    /**
     * Operation batchPutSkuStocksWithHttpInfo
     *
     * @param  \com\jd\openapi\apiClient\sp\product\v0\model\BatchPutSkuStocksRequest $batch_put_sku_stocks_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['batchPutSkuStocks'] to see the possible values for this operation
     *
     * @throws \com\jd\openapi\apiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \com\jd\openapi\apiClient\sp\product\v0\model\BatchPutSkuStocksResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function batchPutSkuStocksWithHttpInfo($batch_put_sku_stocks_request, string $contentType = self::contentTypes['batchPutSkuStocks'][0])
    {
        $request = $this->batchPutSkuStocksRequest($batch_put_sku_stocks_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\com\jd\openapi\apiClient\sp\product\v0\model\BatchPutSkuStocksResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\com\jd\openapi\apiClient\sp\product\v0\model\BatchPutSkuStocksResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com\jd\openapi\apiClient\sp\product\v0\model\BatchPutSkuStocksResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\com\jd\openapi\apiClient\sp\product\v0\model\BatchPutSkuStocksResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com\jd\openapi\apiClient\sp\product\v0\model\BatchPutSkuStocksResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation batchPutSkuStocksAsync
     *
     * @param  \com\jd\openapi\apiClient\sp\product\v0\model\BatchPutSkuStocksRequest $batch_put_sku_stocks_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['batchPutSkuStocks'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function batchPutSkuStocksAsync($batch_put_sku_stocks_request, string $contentType = self::contentTypes['batchPutSkuStocks'][0])
    {
        return $this->batchPutSkuStocksAsyncWithHttpInfo($batch_put_sku_stocks_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation batchPutSkuStocksAsyncWithHttpInfo
     *
     * @param  \com\jd\openapi\apiClient\sp\product\v0\model\BatchPutSkuStocksRequest $batch_put_sku_stocks_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['batchPutSkuStocks'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function batchPutSkuStocksAsyncWithHttpInfo($batch_put_sku_stocks_request, string $contentType = self::contentTypes['batchPutSkuStocks'][0])
    {
        $returnType = '\com\jd\openapi\apiClient\sp\product\v0\model\BatchPutSkuStocksResponse';
        $request = $this->batchPutSkuStocksRequest($batch_put_sku_stocks_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'batchPutSkuStocks'
     *
     * @param  \com\jd\openapi\apiClient\sp\product\v0\model\BatchPutSkuStocksRequest $batch_put_sku_stocks_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['batchPutSkuStocks'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function batchPutSkuStocksRequest($batch_put_sku_stocks_request, string $contentType = self::contentTypes['batchPutSkuStocks'][0])
    {

        // verify the required parameter 'batch_put_sku_stocks_request' is set
        if ($batch_put_sku_stocks_request === null || (is_array($batch_put_sku_stocks_request) && count($batch_put_sku_stocks_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $batch_put_sku_stocks_request when calling batchPutSkuStocks'
            );
        }


        $resourcePath = '/sp-product/v0/sku-stocks/batch';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $pathParams = [];
        $httpBody = '';
        $multipart = false;




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($batch_put_sku_stocks_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($batch_put_sku_stocks_request));
            } else {
                $httpBody = $batch_put_sku_stocks_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }



        $operationHost = $this->config->getHost();
        //get request
        $queryMethods = array("GET", "DELETE");
        if (in_array("PUT", $queryMethods) && $httpBody !== null){
            $getRequestBody = json_decode($httpBody, true);
            if (json_last_error() === JSON_ERROR_NONE) {
                foreach ($getRequestBody as $key => $value) {
                    if (is_array($value)) {
                        $listValue = implode(',', array_map(function($item) {
                            return (string)$item;
                        }, $value));
                        $queryParams[$key] = $listValue;
                    } elseif (is_scalar($value)) {
                        $queryParams[$key] = (string)$value;
                    }
                }
            }

            $httpBody = null;
        }

        $query = ObjectSerializer::buildQuery($queryParams);
        // ����һ�������������洢ϵͳ����
        $systemParams = [];
        $systemParams['appKey'] = $this->config->getAppKey();
        $systemParams['appSecret'] = $this->config->getAppSecret();
        $systemParams['accessToken'] = $this->config->getAccessToken();
        $timestamp = (string)(time() * 1000); // ��ȡ��ǰʱ��������룩
        $systemParams['timestamp'] = $timestamp;

        // ����ǩ��
        $signMap = SignatureCalculator::parameterConvert($systemParams, $queryParams, $httpBody, $pathParams);
        $sign = SignatureCalculator::calculateSignature($this->config->getAppSecret(), $signMap);

        // ����ϵͳͷ��
        $headerParams["X-JOS-Sign"] =  $sign;
        $headerParams["X-JOS-Timestamp"] = $timestamp;
        $headerParams["X-JOS-App-Key"] = $this->config->getAppKey();
        $headerParams["X-JOS-Access-Token"] = $this->config->getAccessToken();
        $headerParams["X-JOS-Sdk-Version"] = "php-v2";

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listSkuStocks
     *
     * @param  \com\jd\openapi\apiClient\sp\product\v0\model\ListSkuStocksRequest $list_sku_stocks_request list_sku_stocks_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listSkuStocks'] to see the possible values for this operation
     *
     * @throws \com\jd\openapi\apiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \com\jd\openapi\apiClient\sp\product\v0\model\ListSkuStocksResponse
     */
    public function listSkuStocks($list_sku_stocks_request, string $contentType = self::contentTypes['listSkuStocks'][0])
    {
        list($response) = $this->listSkuStocksWithHttpInfo($list_sku_stocks_request, $contentType);
        return $response;
    }

    /**
     * Operation listSkuStocksWithHttpInfo
     *
     * @param  \com\jd\openapi\apiClient\sp\product\v0\model\ListSkuStocksRequest $list_sku_stocks_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listSkuStocks'] to see the possible values for this operation
     *
     * @throws \com\jd\openapi\apiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \com\jd\openapi\apiClient\sp\product\v0\model\ListSkuStocksResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function listSkuStocksWithHttpInfo($list_sku_stocks_request, string $contentType = self::contentTypes['listSkuStocks'][0])
    {
        $request = $this->listSkuStocksRequest($list_sku_stocks_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\com\jd\openapi\apiClient\sp\product\v0\model\ListSkuStocksResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\com\jd\openapi\apiClient\sp\product\v0\model\ListSkuStocksResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com\jd\openapi\apiClient\sp\product\v0\model\ListSkuStocksResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\com\jd\openapi\apiClient\sp\product\v0\model\ListSkuStocksResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com\jd\openapi\apiClient\sp\product\v0\model\ListSkuStocksResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation listSkuStocksAsync
     *
     * @param  \com\jd\openapi\apiClient\sp\product\v0\model\ListSkuStocksRequest $list_sku_stocks_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listSkuStocks'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listSkuStocksAsync($list_sku_stocks_request, string $contentType = self::contentTypes['listSkuStocks'][0])
    {
        return $this->listSkuStocksAsyncWithHttpInfo($list_sku_stocks_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listSkuStocksAsyncWithHttpInfo
     *
     * @param  \com\jd\openapi\apiClient\sp\product\v0\model\ListSkuStocksRequest $list_sku_stocks_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listSkuStocks'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listSkuStocksAsyncWithHttpInfo($list_sku_stocks_request, string $contentType = self::contentTypes['listSkuStocks'][0])
    {
        $returnType = '\com\jd\openapi\apiClient\sp\product\v0\model\ListSkuStocksResponse';
        $request = $this->listSkuStocksRequest($list_sku_stocks_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listSkuStocks'
     *
     * @param  \com\jd\openapi\apiClient\sp\product\v0\model\ListSkuStocksRequest $list_sku_stocks_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listSkuStocks'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listSkuStocksRequest($list_sku_stocks_request, string $contentType = self::contentTypes['listSkuStocks'][0])
    {

        // verify the required parameter 'list_sku_stocks_request' is set
        if ($list_sku_stocks_request === null || (is_array($list_sku_stocks_request) && count($list_sku_stocks_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $list_sku_stocks_request when calling listSkuStocks'
            );
        }


        $resourcePath = '/sp-product/v0/sku-stocks';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $pathParams = [];
        $httpBody = '';
        $multipart = false;




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($list_sku_stocks_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($list_sku_stocks_request));
            } else {
                $httpBody = $list_sku_stocks_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }



        $operationHost = $this->config->getHost();
        //get request
        $queryMethods = array("GET", "DELETE");
        if (in_array("GET", $queryMethods) && $httpBody !== null){
            $getRequestBody = json_decode($httpBody, true);
            if (json_last_error() === JSON_ERROR_NONE) {
                foreach ($getRequestBody as $key => $value) {
                    if (is_array($value)) {
                        $listValue = implode(',', array_map(function($item) {
                            return (string)$item;
                        }, $value));
                        $queryParams[$key] = $listValue;
                    } elseif (is_scalar($value)) {
                        $queryParams[$key] = (string)$value;
                    }
                }
            }

            $httpBody = null;
        }

        $query = ObjectSerializer::buildQuery($queryParams);
        // ����һ�������������洢ϵͳ����
        $systemParams = [];
        $systemParams['appKey'] = $this->config->getAppKey();
        $systemParams['appSecret'] = $this->config->getAppSecret();
        $systemParams['accessToken'] = $this->config->getAccessToken();
        $timestamp = (string)(time() * 1000); // ��ȡ��ǰʱ��������룩
        $systemParams['timestamp'] = $timestamp;

        // ����ǩ��
        $signMap = SignatureCalculator::parameterConvert($systemParams, $queryParams, $httpBody, $pathParams);
        $sign = SignatureCalculator::calculateSignature($this->config->getAppSecret(), $signMap);

        // ����ϵͳͷ��
        $headerParams["X-JOS-Sign"] =  $sign;
        $headerParams["X-JOS-Timestamp"] = $timestamp;
        $headerParams["X-JOS-App-Key"] = $this->config->getAppKey();
        $headerParams["X-JOS-Access-Token"] = $this->config->getAccessToken();
        $headerParams["X-JOS-Sdk-Version"] = "php-v2";

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
