<?php
/**
 * LimitBuyStrategiesLimitBuyStrategyDTO
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  com\jd\openapi\apiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */


/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace com\jd\openapi\apiClient\sp\product\v0\model;

use \ArrayAccess;
use \com\jd\openapi\apiClient\ObjectSerializer;

/**
 * LimitBuyStrategiesLimitBuyStrategyDTO Class Doc Comment
 *
 * @category Class
 * @package  com\jd\openapi\apiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class LimitBuyStrategiesLimitBuyStrategyDTO implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'LimitBuyStrategiesLimitBuyStrategyDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'limit_phone_flag' => 'bool',
        'limit_min_num' => 'int',
        'limit_end_time' => 'int',
        'limit_ip_flag' => 'bool',
        'limit_total_num' => 'int',
        'limit_day' => 'int',
        'limit_pin_flag' => 'bool',
        'strategy_status' => 'string',
        'limit_type' => 'string',
        'limit_per_order_num' => 'int',
        'limit_strategy_name' => 'string',
        'value_type' => 'string',
        'strategy_id' => 'int',
        'limit_start_time' => 'int',
        'limit_desc' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'limit_phone_flag' => null,
        'limit_min_num' => 'int32',
        'limit_end_time' => 'int64',
        'limit_ip_flag' => null,
        'limit_total_num' => 'int32',
        'limit_day' => 'int32',
        'limit_pin_flag' => null,
        'strategy_status' => null,
        'limit_type' => null,
        'limit_per_order_num' => 'int32',
        'limit_strategy_name' => null,
        'value_type' => null,
        'strategy_id' => 'int64',
        'limit_start_time' => 'int64',
        'limit_desc' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'limit_phone_flag' => true,
		'limit_min_num' => true,
		'limit_end_time' => true,
		'limit_ip_flag' => true,
		'limit_total_num' => true,
		'limit_day' => true,
		'limit_pin_flag' => true,
		'strategy_status' => true,
		'limit_type' => true,
		'limit_per_order_num' => true,
		'limit_strategy_name' => true,
		'value_type' => true,
		'strategy_id' => true,
		'limit_start_time' => true,
		'limit_desc' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'limit_phone_flag' => 'limitPhoneFlag',
        'limit_min_num' => 'limitMinNum',
        'limit_end_time' => 'limitEndTime',
        'limit_ip_flag' => 'limitIpFlag',
        'limit_total_num' => 'limitTotalNum',
        'limit_day' => 'limitDay',
        'limit_pin_flag' => 'limitPinFlag',
        'strategy_status' => 'strategyStatus',
        'limit_type' => 'limitType',
        'limit_per_order_num' => 'limitPerOrderNum',
        'limit_strategy_name' => 'limitStrategyName',
        'value_type' => 'valueType',
        'strategy_id' => 'strategyId',
        'limit_start_time' => 'limitStartTime',
        'limit_desc' => 'limitDesc'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'limit_phone_flag' => 'setLimitPhoneFlag',
        'limit_min_num' => 'setLimitMinNum',
        'limit_end_time' => 'setLimitEndTime',
        'limit_ip_flag' => 'setLimitIpFlag',
        'limit_total_num' => 'setLimitTotalNum',
        'limit_day' => 'setLimitDay',
        'limit_pin_flag' => 'setLimitPinFlag',
        'strategy_status' => 'setStrategyStatus',
        'limit_type' => 'setLimitType',
        'limit_per_order_num' => 'setLimitPerOrderNum',
        'limit_strategy_name' => 'setLimitStrategyName',
        'value_type' => 'setValueType',
        'strategy_id' => 'setStrategyId',
        'limit_start_time' => 'setLimitStartTime',
        'limit_desc' => 'setLimitDesc'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'limit_phone_flag' => 'getLimitPhoneFlag',
        'limit_min_num' => 'getLimitMinNum',
        'limit_end_time' => 'getLimitEndTime',
        'limit_ip_flag' => 'getLimitIpFlag',
        'limit_total_num' => 'getLimitTotalNum',
        'limit_day' => 'getLimitDay',
        'limit_pin_flag' => 'getLimitPinFlag',
        'strategy_status' => 'getStrategyStatus',
        'limit_type' => 'getLimitType',
        'limit_per_order_num' => 'getLimitPerOrderNum',
        'limit_strategy_name' => 'getLimitStrategyName',
        'value_type' => 'getValueType',
        'strategy_id' => 'getStrategyId',
        'limit_start_time' => 'getLimitStartTime',
        'limit_desc' => 'getLimitDesc'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('limit_phone_flag', $data ?? [], null);
        $this->setIfExists('limit_min_num', $data ?? [], null);
        $this->setIfExists('limit_end_time', $data ?? [], null);
        $this->setIfExists('limit_ip_flag', $data ?? [], null);
        $this->setIfExists('limit_total_num', $data ?? [], null);
        $this->setIfExists('limit_day', $data ?? [], null);
        $this->setIfExists('limit_pin_flag', $data ?? [], null);
        $this->setIfExists('strategy_status', $data ?? [], null);
        $this->setIfExists('limit_type', $data ?? [], null);
        $this->setIfExists('limit_per_order_num', $data ?? [], null);
        $this->setIfExists('limit_strategy_name', $data ?? [], null);
        $this->setIfExists('value_type', $data ?? [], null);
        $this->setIfExists('strategy_id', $data ?? [], null);
        $this->setIfExists('limit_start_time', $data ?? [], null);
        $this->setIfExists('limit_desc', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets limit_phone_flag
     *
     * @return bool|null
     */
    public function getLimitPhoneFlag()
    {
        return $this->container['limit_phone_flag'];
    }

    /**
     * Sets limit_phone_flag
     *
     * @param bool|null $limit_phone_flag limit_phone_flag
     *
     * @return self
     */
    public function setLimitPhoneFlag($limit_phone_flag)
    {
        if (is_null($limit_phone_flag)) {
            array_push($this->openAPINullablesSetToNull, 'limit_phone_flag');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('limit_phone_flag', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['limit_phone_flag'] = $limit_phone_flag;

        return $this;
    }

    /**
     * Gets limit_min_num
     *
     * @return int|null
     */
    public function getLimitMinNum()
    {
        return $this->container['limit_min_num'];
    }

    /**
     * Sets limit_min_num
     *
     * @param int|null $limit_min_num limit_min_num
     *
     * @return self
     */
    public function setLimitMinNum($limit_min_num)
    {
        if (is_null($limit_min_num)) {
            array_push($this->openAPINullablesSetToNull, 'limit_min_num');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('limit_min_num', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['limit_min_num'] = $limit_min_num;

        return $this;
    }

    /**
     * Gets limit_end_time
     *
     * @return int|null
     */
    public function getLimitEndTime()
    {
        return $this->container['limit_end_time'];
    }

    /**
     * Sets limit_end_time
     *
     * @param int|null $limit_end_time limit_end_time
     *
     * @return self
     */
    public function setLimitEndTime($limit_end_time)
    {
        if (is_null($limit_end_time)) {
            array_push($this->openAPINullablesSetToNull, 'limit_end_time');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('limit_end_time', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['limit_end_time'] = $limit_end_time;

        return $this;
    }

    /**
     * Gets limit_ip_flag
     *
     * @return bool|null
     */
    public function getLimitIpFlag()
    {
        return $this->container['limit_ip_flag'];
    }

    /**
     * Sets limit_ip_flag
     *
     * @param bool|null $limit_ip_flag limit_ip_flag
     *
     * @return self
     */
    public function setLimitIpFlag($limit_ip_flag)
    {
        if (is_null($limit_ip_flag)) {
            array_push($this->openAPINullablesSetToNull, 'limit_ip_flag');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('limit_ip_flag', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['limit_ip_flag'] = $limit_ip_flag;

        return $this;
    }

    /**
     * Gets limit_total_num
     *
     * @return int|null
     */
    public function getLimitTotalNum()
    {
        return $this->container['limit_total_num'];
    }

    /**
     * Sets limit_total_num
     *
     * @param int|null $limit_total_num limit_total_num
     *
     * @return self
     */
    public function setLimitTotalNum($limit_total_num)
    {
        if (is_null($limit_total_num)) {
            array_push($this->openAPINullablesSetToNull, 'limit_total_num');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('limit_total_num', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['limit_total_num'] = $limit_total_num;

        return $this;
    }

    /**
     * Gets limit_day
     *
     * @return int|null
     */
    public function getLimitDay()
    {
        return $this->container['limit_day'];
    }

    /**
     * Sets limit_day
     *
     * @param int|null $limit_day limit_day
     *
     * @return self
     */
    public function setLimitDay($limit_day)
    {
        if (is_null($limit_day)) {
            array_push($this->openAPINullablesSetToNull, 'limit_day');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('limit_day', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['limit_day'] = $limit_day;

        return $this;
    }

    /**
     * Gets limit_pin_flag
     *
     * @return bool|null
     */
    public function getLimitPinFlag()
    {
        return $this->container['limit_pin_flag'];
    }

    /**
     * Sets limit_pin_flag
     *
     * @param bool|null $limit_pin_flag limit_pin_flag
     *
     * @return self
     */
    public function setLimitPinFlag($limit_pin_flag)
    {
        if (is_null($limit_pin_flag)) {
            array_push($this->openAPINullablesSetToNull, 'limit_pin_flag');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('limit_pin_flag', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['limit_pin_flag'] = $limit_pin_flag;

        return $this;
    }

    /**
     * Gets strategy_status
     *
     * @return string|null
     */
    public function getStrategyStatus()
    {
        return $this->container['strategy_status'];
    }

    /**
     * Sets strategy_status
     *
     * @param string|null $strategy_status strategy_status
     *
     * @return self
     */
    public function setStrategyStatus($strategy_status)
    {
        if (is_null($strategy_status)) {
            array_push($this->openAPINullablesSetToNull, 'strategy_status');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('strategy_status', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['strategy_status'] = $strategy_status;

        return $this;
    }

    /**
     * Gets limit_type
     *
     * @return string|null
     */
    public function getLimitType()
    {
        return $this->container['limit_type'];
    }

    /**
     * Sets limit_type
     *
     * @param string|null $limit_type limit_type
     *
     * @return self
     */
    public function setLimitType($limit_type)
    {
        if (is_null($limit_type)) {
            array_push($this->openAPINullablesSetToNull, 'limit_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('limit_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['limit_type'] = $limit_type;

        return $this;
    }

    /**
     * Gets limit_per_order_num
     *
     * @return int|null
     */
    public function getLimitPerOrderNum()
    {
        return $this->container['limit_per_order_num'];
    }

    /**
     * Sets limit_per_order_num
     *
     * @param int|null $limit_per_order_num limit_per_order_num
     *
     * @return self
     */
    public function setLimitPerOrderNum($limit_per_order_num)
    {
        if (is_null($limit_per_order_num)) {
            array_push($this->openAPINullablesSetToNull, 'limit_per_order_num');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('limit_per_order_num', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['limit_per_order_num'] = $limit_per_order_num;

        return $this;
    }

    /**
     * Gets limit_strategy_name
     *
     * @return string|null
     */
    public function getLimitStrategyName()
    {
        return $this->container['limit_strategy_name'];
    }

    /**
     * Sets limit_strategy_name
     *
     * @param string|null $limit_strategy_name limit_strategy_name
     *
     * @return self
     */
    public function setLimitStrategyName($limit_strategy_name)
    {
        if (is_null($limit_strategy_name)) {
            array_push($this->openAPINullablesSetToNull, 'limit_strategy_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('limit_strategy_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['limit_strategy_name'] = $limit_strategy_name;

        return $this;
    }

    /**
     * Gets value_type
     *
     * @return string|null
     */
    public function getValueType()
    {
        return $this->container['value_type'];
    }

    /**
     * Sets value_type
     *
     * @param string|null $value_type value_type
     *
     * @return self
     */
    public function setValueType($value_type)
    {
        if (is_null($value_type)) {
            array_push($this->openAPINullablesSetToNull, 'value_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('value_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['value_type'] = $value_type;

        return $this;
    }

    /**
     * Gets strategy_id
     *
     * @return int|null
     */
    public function getStrategyId()
    {
        return $this->container['strategy_id'];
    }

    /**
     * Sets strategy_id
     *
     * @param int|null $strategy_id strategy_id
     *
     * @return self
     */
    public function setStrategyId($strategy_id)
    {
        if (is_null($strategy_id)) {
            array_push($this->openAPINullablesSetToNull, 'strategy_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('strategy_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['strategy_id'] = $strategy_id;

        return $this;
    }

    /**
     * Gets limit_start_time
     *
     * @return int|null
     */
    public function getLimitStartTime()
    {
        return $this->container['limit_start_time'];
    }

    /**
     * Sets limit_start_time
     *
     * @param int|null $limit_start_time limit_start_time
     *
     * @return self
     */
    public function setLimitStartTime($limit_start_time)
    {
        if (is_null($limit_start_time)) {
            array_push($this->openAPINullablesSetToNull, 'limit_start_time');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('limit_start_time', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['limit_start_time'] = $limit_start_time;

        return $this;
    }

    /**
     * Gets limit_desc
     *
     * @return string|null
     */
    public function getLimitDesc()
    {
        return $this->container['limit_desc'];
    }

    /**
     * Sets limit_desc
     *
     * @param string|null $limit_desc limit_desc
     *
     * @return self
     */
    public function setLimitDesc($limit_desc)
    {
        if (is_null($limit_desc)) {
            array_push($this->openAPINullablesSetToNull, 'limit_desc');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('limit_desc', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['limit_desc'] = $limit_desc;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


