<?php
/**
 * MaterialExperimentRulesMaterialExperimentRuleDTO
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  com\jd\openapi\apiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */


/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace com\jd\openapi\apiClient\sp\product\v0\model;

use \ArrayAccess;
use \com\jd\openapi\apiClient\ObjectSerializer;

/**
 * MaterialExperimentRulesMaterialExperimentRuleDTO Class Doc Comment
 *
 * @category Class
 * @package  com\jd\openapi\apiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class MaterialExperimentRulesMaterialExperimentRuleDTO implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'MaterialExperimentRulesMaterialExperimentRuleDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'can_create_flag' => 'bool',
        'left_ratio' => 'int',
        'min_ration' => 'int',
        'max_version_num' => 'int',
        'route_ratio' => 'int',
        'lock_ratio_flag' => 'bool',
        'message' => 'string',
        'sku_id' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'can_create_flag' => null,
        'left_ratio' => 'int32',
        'min_ration' => 'int32',
        'max_version_num' => 'int32',
        'route_ratio' => 'int32',
        'lock_ratio_flag' => null,
        'message' => null,
        'sku_id' => 'int64'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'can_create_flag' => true,
		'left_ratio' => true,
		'min_ration' => true,
		'max_version_num' => true,
		'route_ratio' => true,
		'lock_ratio_flag' => true,
		'message' => true,
		'sku_id' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'can_create_flag' => 'canCreateFlag',
        'left_ratio' => 'leftRatio',
        'min_ration' => 'minRation',
        'max_version_num' => 'maxVersionNum',
        'route_ratio' => 'routeRatio',
        'lock_ratio_flag' => 'lockRatioFlag',
        'message' => 'message',
        'sku_id' => 'skuId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'can_create_flag' => 'setCanCreateFlag',
        'left_ratio' => 'setLeftRatio',
        'min_ration' => 'setMinRation',
        'max_version_num' => 'setMaxVersionNum',
        'route_ratio' => 'setRouteRatio',
        'lock_ratio_flag' => 'setLockRatioFlag',
        'message' => 'setMessage',
        'sku_id' => 'setSkuId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'can_create_flag' => 'getCanCreateFlag',
        'left_ratio' => 'getLeftRatio',
        'min_ration' => 'getMinRation',
        'max_version_num' => 'getMaxVersionNum',
        'route_ratio' => 'getRouteRatio',
        'lock_ratio_flag' => 'getLockRatioFlag',
        'message' => 'getMessage',
        'sku_id' => 'getSkuId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('can_create_flag', $data ?? [], null);
        $this->setIfExists('left_ratio', $data ?? [], null);
        $this->setIfExists('min_ration', $data ?? [], null);
        $this->setIfExists('max_version_num', $data ?? [], null);
        $this->setIfExists('route_ratio', $data ?? [], null);
        $this->setIfExists('lock_ratio_flag', $data ?? [], null);
        $this->setIfExists('message', $data ?? [], null);
        $this->setIfExists('sku_id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets can_create_flag
     *
     * @return bool|null
     */
    public function getCanCreateFlag()
    {
        return $this->container['can_create_flag'];
    }

    /**
     * Sets can_create_flag
     *
     * @param bool|null $can_create_flag can_create_flag
     *
     * @return self
     */
    public function setCanCreateFlag($can_create_flag)
    {
        if (is_null($can_create_flag)) {
            array_push($this->openAPINullablesSetToNull, 'can_create_flag');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('can_create_flag', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['can_create_flag'] = $can_create_flag;

        return $this;
    }

    /**
     * Gets left_ratio
     *
     * @return int|null
     */
    public function getLeftRatio()
    {
        return $this->container['left_ratio'];
    }

    /**
     * Sets left_ratio
     *
     * @param int|null $left_ratio left_ratio
     *
     * @return self
     */
    public function setLeftRatio($left_ratio)
    {
        if (is_null($left_ratio)) {
            array_push($this->openAPINullablesSetToNull, 'left_ratio');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('left_ratio', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['left_ratio'] = $left_ratio;

        return $this;
    }

    /**
     * Gets min_ration
     *
     * @return int|null
     */
    public function getMinRation()
    {
        return $this->container['min_ration'];
    }

    /**
     * Sets min_ration
     *
     * @param int|null $min_ration min_ration
     *
     * @return self
     */
    public function setMinRation($min_ration)
    {
        if (is_null($min_ration)) {
            array_push($this->openAPINullablesSetToNull, 'min_ration');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('min_ration', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['min_ration'] = $min_ration;

        return $this;
    }

    /**
     * Gets max_version_num
     *
     * @return int|null
     */
    public function getMaxVersionNum()
    {
        return $this->container['max_version_num'];
    }

    /**
     * Sets max_version_num
     *
     * @param int|null $max_version_num max_version_num
     *
     * @return self
     */
    public function setMaxVersionNum($max_version_num)
    {
        if (is_null($max_version_num)) {
            array_push($this->openAPINullablesSetToNull, 'max_version_num');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('max_version_num', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['max_version_num'] = $max_version_num;

        return $this;
    }

    /**
     * Gets route_ratio
     *
     * @return int|null
     */
    public function getRouteRatio()
    {
        return $this->container['route_ratio'];
    }

    /**
     * Sets route_ratio
     *
     * @param int|null $route_ratio route_ratio
     *
     * @return self
     */
    public function setRouteRatio($route_ratio)
    {
        if (is_null($route_ratio)) {
            array_push($this->openAPINullablesSetToNull, 'route_ratio');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('route_ratio', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['route_ratio'] = $route_ratio;

        return $this;
    }

    /**
     * Gets lock_ratio_flag
     *
     * @return bool|null
     */
    public function getLockRatioFlag()
    {
        return $this->container['lock_ratio_flag'];
    }

    /**
     * Sets lock_ratio_flag
     *
     * @param bool|null $lock_ratio_flag lock_ratio_flag
     *
     * @return self
     */
    public function setLockRatioFlag($lock_ratio_flag)
    {
        if (is_null($lock_ratio_flag)) {
            array_push($this->openAPINullablesSetToNull, 'lock_ratio_flag');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('lock_ratio_flag', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['lock_ratio_flag'] = $lock_ratio_flag;

        return $this;
    }

    /**
     * Gets message
     *
     * @return string|null
     */
    public function getMessage()
    {
        return $this->container['message'];
    }

    /**
     * Sets message
     *
     * @param string|null $message message
     *
     * @return self
     */
    public function setMessage($message)
    {
        if (is_null($message)) {
            array_push($this->openAPINullablesSetToNull, 'message');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('message', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['message'] = $message;

        return $this;
    }

    /**
     * Gets sku_id
     *
     * @return int|null
     */
    public function getSkuId()
    {
        return $this->container['sku_id'];
    }

    /**
     * Sets sku_id
     *
     * @param int|null $sku_id sku_id
     *
     * @return self
     */
    public function setSkuId($sku_id)
    {
        if (is_null($sku_id)) {
            array_push($this->openAPINullablesSetToNull, 'sku_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('sku_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['sku_id'] = $sku_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


