<?php
/**
 * MediaZonesVideosMediaZoneVideoDTO
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  com\jd\openapi\apiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */


/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace com\jd\openapi\apiClient\sp\product\v0\model;

use \ArrayAccess;
use \com\jd\openapi\apiClient\ObjectSerializer;

/**
 * MediaZonesVideosMediaZoneVideoDTO Class Doc Comment
 *
 * @category Class
 * @package  com\jd\openapi\apiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class MediaZonesVideosMediaZoneVideoDTO implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'MediaZonesVideosMediaZoneVideoDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'modified_time' => 'int',
        'index_image' => 'string',
        'video_type' => 'int',
        'video_desc' => 'string',
        'video_id' => 'int',
        'video_size' => 'int',
        'play_url_list' => '\com\jd\openapi\apiClient\sp\product\v0\model\MediaZonesVideosMediaZoneVideoPlayUrlDTO[]',
        'duration' => 'int',
        'video_name' => 'string',
        'created_time' => 'int',
        'audit_desc' => 'string',
        'jd_video_id' => 'int',
        'status' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'modified_time' => 'int64',
        'index_image' => null,
        'video_type' => 'int32',
        'video_desc' => null,
        'video_id' => 'int64',
        'video_size' => 'int64',
        'play_url_list' => null,
        'duration' => 'int32',
        'video_name' => null,
        'created_time' => 'int64',
        'audit_desc' => null,
        'jd_video_id' => 'int64',
        'status' => 'int32'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'modified_time' => true,
		'index_image' => true,
		'video_type' => true,
		'video_desc' => true,
		'video_id' => true,
		'video_size' => true,
		'play_url_list' => false,
		'duration' => true,
		'video_name' => true,
		'created_time' => true,
		'audit_desc' => true,
		'jd_video_id' => true,
		'status' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'modified_time' => 'modifiedTime',
        'index_image' => 'indexImage',
        'video_type' => 'videoType',
        'video_desc' => 'videoDesc',
        'video_id' => 'videoId',
        'video_size' => 'videoSize',
        'play_url_list' => 'playUrlList',
        'duration' => 'duration',
        'video_name' => 'videoName',
        'created_time' => 'createdTime',
        'audit_desc' => 'auditDesc',
        'jd_video_id' => 'jdVideoId',
        'status' => 'status'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'modified_time' => 'setModifiedTime',
        'index_image' => 'setIndexImage',
        'video_type' => 'setVideoType',
        'video_desc' => 'setVideoDesc',
        'video_id' => 'setVideoId',
        'video_size' => 'setVideoSize',
        'play_url_list' => 'setPlayUrlList',
        'duration' => 'setDuration',
        'video_name' => 'setVideoName',
        'created_time' => 'setCreatedTime',
        'audit_desc' => 'setAuditDesc',
        'jd_video_id' => 'setJdVideoId',
        'status' => 'setStatus'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'modified_time' => 'getModifiedTime',
        'index_image' => 'getIndexImage',
        'video_type' => 'getVideoType',
        'video_desc' => 'getVideoDesc',
        'video_id' => 'getVideoId',
        'video_size' => 'getVideoSize',
        'play_url_list' => 'getPlayUrlList',
        'duration' => 'getDuration',
        'video_name' => 'getVideoName',
        'created_time' => 'getCreatedTime',
        'audit_desc' => 'getAuditDesc',
        'jd_video_id' => 'getJdVideoId',
        'status' => 'getStatus'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('modified_time', $data ?? [], null);
        $this->setIfExists('index_image', $data ?? [], null);
        $this->setIfExists('video_type', $data ?? [], null);
        $this->setIfExists('video_desc', $data ?? [], null);
        $this->setIfExists('video_id', $data ?? [], null);
        $this->setIfExists('video_size', $data ?? [], null);
        $this->setIfExists('play_url_list', $data ?? [], null);
        $this->setIfExists('duration', $data ?? [], null);
        $this->setIfExists('video_name', $data ?? [], null);
        $this->setIfExists('created_time', $data ?? [], null);
        $this->setIfExists('audit_desc', $data ?? [], null);
        $this->setIfExists('jd_video_id', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets modified_time
     *
     * @return int|null
     */
    public function getModifiedTime()
    {
        return $this->container['modified_time'];
    }

    /**
     * Sets modified_time
     *
     * @param int|null $modified_time modified_time
     *
     * @return self
     */
    public function setModifiedTime($modified_time)
    {
        if (is_null($modified_time)) {
            array_push($this->openAPINullablesSetToNull, 'modified_time');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('modified_time', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['modified_time'] = $modified_time;

        return $this;
    }

    /**
     * Gets index_image
     *
     * @return string|null
     */
    public function getIndexImage()
    {
        return $this->container['index_image'];
    }

    /**
     * Sets index_image
     *
     * @param string|null $index_image index_image
     *
     * @return self
     */
    public function setIndexImage($index_image)
    {
        if (is_null($index_image)) {
            array_push($this->openAPINullablesSetToNull, 'index_image');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('index_image', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['index_image'] = $index_image;

        return $this;
    }

    /**
     * Gets video_type
     *
     * @return int|null
     */
    public function getVideoType()
    {
        return $this->container['video_type'];
    }

    /**
     * Sets video_type
     *
     * @param int|null $video_type video_type
     *
     * @return self
     */
    public function setVideoType($video_type)
    {
        if (is_null($video_type)) {
            array_push($this->openAPINullablesSetToNull, 'video_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('video_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['video_type'] = $video_type;

        return $this;
    }

    /**
     * Gets video_desc
     *
     * @return string|null
     */
    public function getVideoDesc()
    {
        return $this->container['video_desc'];
    }

    /**
     * Sets video_desc
     *
     * @param string|null $video_desc video_desc
     *
     * @return self
     */
    public function setVideoDesc($video_desc)
    {
        if (is_null($video_desc)) {
            array_push($this->openAPINullablesSetToNull, 'video_desc');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('video_desc', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['video_desc'] = $video_desc;

        return $this;
    }

    /**
     * Gets video_id
     *
     * @return int|null
     */
    public function getVideoId()
    {
        return $this->container['video_id'];
    }

    /**
     * Sets video_id
     *
     * @param int|null $video_id video_id
     *
     * @return self
     */
    public function setVideoId($video_id)
    {
        if (is_null($video_id)) {
            array_push($this->openAPINullablesSetToNull, 'video_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('video_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['video_id'] = $video_id;

        return $this;
    }

    /**
     * Gets video_size
     *
     * @return int|null
     */
    public function getVideoSize()
    {
        return $this->container['video_size'];
    }

    /**
     * Sets video_size
     *
     * @param int|null $video_size video_size
     *
     * @return self
     */
    public function setVideoSize($video_size)
    {
        if (is_null($video_size)) {
            array_push($this->openAPINullablesSetToNull, 'video_size');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('video_size', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['video_size'] = $video_size;

        return $this;
    }

    /**
     * Gets play_url_list
     *
     * @return \com\jd\openapi\apiClient\sp\product\v0\model\MediaZonesVideosMediaZoneVideoPlayUrlDTO[]|null
     */
    public function getPlayUrlList()
    {
        return $this->container['play_url_list'];
    }

    /**
     * Sets play_url_list
     *
     * @param \com\jd\openapi\apiClient\sp\product\v0\model\MediaZonesVideosMediaZoneVideoPlayUrlDTO[]|null $play_url_list play_url_list
     *
     * @return self
     */
    public function setPlayUrlList($play_url_list)
    {
        if (is_null($play_url_list)) {
            throw new \InvalidArgumentException('non-nullable play_url_list cannot be null');
        }
        $this->container['play_url_list'] = $play_url_list;

        return $this;
    }

    /**
     * Gets duration
     *
     * @return int|null
     */
    public function getDuration()
    {
        return $this->container['duration'];
    }

    /**
     * Sets duration
     *
     * @param int|null $duration duration
     *
     * @return self
     */
    public function setDuration($duration)
    {
        if (is_null($duration)) {
            array_push($this->openAPINullablesSetToNull, 'duration');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('duration', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['duration'] = $duration;

        return $this;
    }

    /**
     * Gets video_name
     *
     * @return string|null
     */
    public function getVideoName()
    {
        return $this->container['video_name'];
    }

    /**
     * Sets video_name
     *
     * @param string|null $video_name video_name
     *
     * @return self
     */
    public function setVideoName($video_name)
    {
        if (is_null($video_name)) {
            array_push($this->openAPINullablesSetToNull, 'video_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('video_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['video_name'] = $video_name;

        return $this;
    }

    /**
     * Gets created_time
     *
     * @return int|null
     */
    public function getCreatedTime()
    {
        return $this->container['created_time'];
    }

    /**
     * Sets created_time
     *
     * @param int|null $created_time created_time
     *
     * @return self
     */
    public function setCreatedTime($created_time)
    {
        if (is_null($created_time)) {
            array_push($this->openAPINullablesSetToNull, 'created_time');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('created_time', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['created_time'] = $created_time;

        return $this;
    }

    /**
     * Gets audit_desc
     *
     * @return string|null
     */
    public function getAuditDesc()
    {
        return $this->container['audit_desc'];
    }

    /**
     * Sets audit_desc
     *
     * @param string|null $audit_desc audit_desc
     *
     * @return self
     */
    public function setAuditDesc($audit_desc)
    {
        if (is_null($audit_desc)) {
            array_push($this->openAPINullablesSetToNull, 'audit_desc');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('audit_desc', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['audit_desc'] = $audit_desc;

        return $this;
    }

    /**
     * Gets jd_video_id
     *
     * @return int|null
     */
    public function getJdVideoId()
    {
        return $this->container['jd_video_id'];
    }

    /**
     * Sets jd_video_id
     *
     * @param int|null $jd_video_id jd_video_id
     *
     * @return self
     */
    public function setJdVideoId($jd_video_id)
    {
        if (is_null($jd_video_id)) {
            array_push($this->openAPINullablesSetToNull, 'jd_video_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('jd_video_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['jd_video_id'] = $jd_video_id;

        return $this;
    }

    /**
     * Gets status
     *
     * @return int|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param int|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            array_push($this->openAPINullablesSetToNull, 'status');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('status', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['status'] = $status;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


