<?php
/**
 * PatchProductAppliesRequest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  com\jd\openapi\apiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */


/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace com\jd\openapi\apiClient\sp\product\v0\model;

use \ArrayAccess;
use \com\jd\openapi\apiClient\ObjectSerializer;

/**
 * PatchProductAppliesRequest Class Doc Comment
 *
 * @category Class
 * @package  com\jd\openapi\apiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PatchProductAppliesRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PatchProductAppliesRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'product_apply_dto' => '\com\jd\openapi\apiClient\sp\product\v0\model\ProductAppliesProductApplyDTO',
        'op_type' => 'int',
        'target_sku_id_groups' => '\com\jd\openapi\apiClient\sp\product\v0\model\ProductAppliesTargetSkuGroupDTO[]',
        'patch_operation_list' => '\com\jd\openapi\apiClient\sp\product\v0\model\ProductAppliesPatchOperationParam[]',
        'scene' => 'string',
        'product_info' => '\com\jd\openapi\apiClient\sp\product\v0\model\ProductAppliesProductInfoDTO'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'product_apply_dto' => null,
        'op_type' => 'int32',
        'target_sku_id_groups' => null,
        'patch_operation_list' => null,
        'scene' => null,
        'product_info' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'product_apply_dto' => false,
		'op_type' => true,
		'target_sku_id_groups' => false,
		'patch_operation_list' => false,
		'scene' => true,
		'product_info' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'product_apply_dto' => 'productApplyDTO',
        'op_type' => 'opType',
        'target_sku_id_groups' => 'targetSkuIdGroups',
        'patch_operation_list' => 'patchOperationList',
        'scene' => 'scene',
        'product_info' => 'productInfo'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'product_apply_dto' => 'setProductApplyDto',
        'op_type' => 'setOpType',
        'target_sku_id_groups' => 'setTargetSkuIdGroups',
        'patch_operation_list' => 'setPatchOperationList',
        'scene' => 'setScene',
        'product_info' => 'setProductInfo'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'product_apply_dto' => 'getProductApplyDto',
        'op_type' => 'getOpType',
        'target_sku_id_groups' => 'getTargetSkuIdGroups',
        'patch_operation_list' => 'getPatchOperationList',
        'scene' => 'getScene',
        'product_info' => 'getProductInfo'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('product_apply_dto', $data ?? [], null);
        $this->setIfExists('op_type', $data ?? [], null);
        $this->setIfExists('target_sku_id_groups', $data ?? [], null);
        $this->setIfExists('patch_operation_list', $data ?? [], null);
        $this->setIfExists('scene', $data ?? [], null);
        $this->setIfExists('product_info', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets product_apply_dto
     *
     * @return \com\jd\openapi\apiClient\sp\product\v0\model\ProductAppliesProductApplyDTO|null
     */
    public function getProductApplyDto()
    {
        return $this->container['product_apply_dto'];
    }

    /**
     * Sets product_apply_dto
     *
     * @param \com\jd\openapi\apiClient\sp\product\v0\model\ProductAppliesProductApplyDTO|null $product_apply_dto product_apply_dto
     *
     * @return self
     */
    public function setProductApplyDto($product_apply_dto)
    {
        if (is_null($product_apply_dto)) {
            throw new \InvalidArgumentException('non-nullable product_apply_dto cannot be null');
        }
        $this->container['product_apply_dto'] = $product_apply_dto;

        return $this;
    }

    /**
     * Gets op_type
     *
     * @return int|null
     */
    public function getOpType()
    {
        return $this->container['op_type'];
    }

    /**
     * Sets op_type
     *
     * @param int|null $op_type op_type
     *
     * @return self
     */
    public function setOpType($op_type)
    {
        if (is_null($op_type)) {
            array_push($this->openAPINullablesSetToNull, 'op_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('op_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['op_type'] = $op_type;

        return $this;
    }

    /**
     * Gets target_sku_id_groups
     *
     * @return \com\jd\openapi\apiClient\sp\product\v0\model\ProductAppliesTargetSkuGroupDTO[]|null
     */
    public function getTargetSkuIdGroups()
    {
        return $this->container['target_sku_id_groups'];
    }

    /**
     * Sets target_sku_id_groups
     *
     * @param \com\jd\openapi\apiClient\sp\product\v0\model\ProductAppliesTargetSkuGroupDTO[]|null $target_sku_id_groups target_sku_id_groups
     *
     * @return self
     */
    public function setTargetSkuIdGroups($target_sku_id_groups)
    {
        if (is_null($target_sku_id_groups)) {
            throw new \InvalidArgumentException('non-nullable target_sku_id_groups cannot be null');
        }
        $this->container['target_sku_id_groups'] = $target_sku_id_groups;

        return $this;
    }

    /**
     * Gets patch_operation_list
     *
     * @return \com\jd\openapi\apiClient\sp\product\v0\model\ProductAppliesPatchOperationParam[]|null
     */
    public function getPatchOperationList()
    {
        return $this->container['patch_operation_list'];
    }

    /**
     * Sets patch_operation_list
     *
     * @param \com\jd\openapi\apiClient\sp\product\v0\model\ProductAppliesPatchOperationParam[]|null $patch_operation_list patch_operation_list
     *
     * @return self
     */
    public function setPatchOperationList($patch_operation_list)
    {
        if (is_null($patch_operation_list)) {
            throw new \InvalidArgumentException('non-nullable patch_operation_list cannot be null');
        }
        $this->container['patch_operation_list'] = $patch_operation_list;

        return $this;
    }

    /**
     * Gets scene
     *
     * @return string|null
     */
    public function getScene()
    {
        return $this->container['scene'];
    }

    /**
     * Sets scene
     *
     * @param string|null $scene scene
     *
     * @return self
     */
    public function setScene($scene)
    {
        if (is_null($scene)) {
            array_push($this->openAPINullablesSetToNull, 'scene');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('scene', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['scene'] = $scene;

        return $this;
    }

    /**
     * Gets product_info
     *
     * @return \com\jd\openapi\apiClient\sp\product\v0\model\ProductAppliesProductInfoDTO|null
     */
    public function getProductInfo()
    {
        return $this->container['product_info'];
    }

    /**
     * Sets product_info
     *
     * @param \com\jd\openapi\apiClient\sp\product\v0\model\ProductAppliesProductInfoDTO|null $product_info product_info
     *
     * @return self
     */
    public function setProductInfo($product_info)
    {
        if (is_null($product_info)) {
            throw new \InvalidArgumentException('non-nullable product_info cannot be null');
        }
        $this->container['product_info'] = $product_info;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


