<?php
/**
 * ViolatingProductsCommonInfoDTO
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  com\jd\openapi\apiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */


/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace com\jd\openapi\apiClient\sp\product\v0\model;

use \ArrayAccess;
use \com\jd\openapi\apiClient\ObjectSerializer;

/**
 * ViolatingProductsCommonInfoDTO Class Doc Comment
 *
 * @category Class
 * @package  com\jd\openapi\apiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ViolatingProductsCommonInfoDTO implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ViolatingProductsCommonInfoDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'field_key' => 'string',
        'violation_info' => '\com\jd\openapi\apiClient\sp\product\v0\model\ViolatingProductsViolationInfoDTO',
        'field_value_type' => 'int',
        'field_key_name' => 'string',
        'field_value_info_list' => '\com\jd\openapi\apiClient\sp\product\v0\model\ViolatingProductsFieldValueInfoDTO[]',
        'field_value_info_vo_list' => '\com\jd\openapi\apiClient\sp\product\v0\model\ViolatingProductsFieldValueInfoDTO[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'field_key' => null,
        'violation_info' => null,
        'field_value_type' => 'int32',
        'field_key_name' => null,
        'field_value_info_list' => null,
        'field_value_info_vo_list' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'field_key' => true,
		'violation_info' => false,
		'field_value_type' => true,
		'field_key_name' => true,
		'field_value_info_list' => false,
		'field_value_info_vo_list' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'field_key' => 'fieldKey',
        'violation_info' => 'violationInfo',
        'field_value_type' => 'fieldValueType',
        'field_key_name' => 'fieldKeyName',
        'field_value_info_list' => 'fieldValueInfoList',
        'field_value_info_vo_list' => 'fieldValueInfoVOList'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'field_key' => 'setFieldKey',
        'violation_info' => 'setViolationInfo',
        'field_value_type' => 'setFieldValueType',
        'field_key_name' => 'setFieldKeyName',
        'field_value_info_list' => 'setFieldValueInfoList',
        'field_value_info_vo_list' => 'setFieldValueInfoVoList'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'field_key' => 'getFieldKey',
        'violation_info' => 'getViolationInfo',
        'field_value_type' => 'getFieldValueType',
        'field_key_name' => 'getFieldKeyName',
        'field_value_info_list' => 'getFieldValueInfoList',
        'field_value_info_vo_list' => 'getFieldValueInfoVoList'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('field_key', $data ?? [], null);
        $this->setIfExists('violation_info', $data ?? [], null);
        $this->setIfExists('field_value_type', $data ?? [], null);
        $this->setIfExists('field_key_name', $data ?? [], null);
        $this->setIfExists('field_value_info_list', $data ?? [], null);
        $this->setIfExists('field_value_info_vo_list', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets field_key
     *
     * @return string|null
     */
    public function getFieldKey()
    {
        return $this->container['field_key'];
    }

    /**
     * Sets field_key
     *
     * @param string|null $field_key field_key
     *
     * @return self
     */
    public function setFieldKey($field_key)
    {
        if (is_null($field_key)) {
            array_push($this->openAPINullablesSetToNull, 'field_key');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('field_key', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['field_key'] = $field_key;

        return $this;
    }

    /**
     * Gets violation_info
     *
     * @return \com\jd\openapi\apiClient\sp\product\v0\model\ViolatingProductsViolationInfoDTO|null
     */
    public function getViolationInfo()
    {
        return $this->container['violation_info'];
    }

    /**
     * Sets violation_info
     *
     * @param \com\jd\openapi\apiClient\sp\product\v0\model\ViolatingProductsViolationInfoDTO|null $violation_info violation_info
     *
     * @return self
     */
    public function setViolationInfo($violation_info)
    {
        if (is_null($violation_info)) {
            throw new \InvalidArgumentException('non-nullable violation_info cannot be null');
        }
        $this->container['violation_info'] = $violation_info;

        return $this;
    }

    /**
     * Gets field_value_type
     *
     * @return int|null
     */
    public function getFieldValueType()
    {
        return $this->container['field_value_type'];
    }

    /**
     * Sets field_value_type
     *
     * @param int|null $field_value_type field_value_type
     *
     * @return self
     */
    public function setFieldValueType($field_value_type)
    {
        if (is_null($field_value_type)) {
            array_push($this->openAPINullablesSetToNull, 'field_value_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('field_value_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['field_value_type'] = $field_value_type;

        return $this;
    }

    /**
     * Gets field_key_name
     *
     * @return string|null
     */
    public function getFieldKeyName()
    {
        return $this->container['field_key_name'];
    }

    /**
     * Sets field_key_name
     *
     * @param string|null $field_key_name field_key_name
     *
     * @return self
     */
    public function setFieldKeyName($field_key_name)
    {
        if (is_null($field_key_name)) {
            array_push($this->openAPINullablesSetToNull, 'field_key_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('field_key_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['field_key_name'] = $field_key_name;

        return $this;
    }

    /**
     * Gets field_value_info_list
     *
     * @return \com\jd\openapi\apiClient\sp\product\v0\model\ViolatingProductsFieldValueInfoDTO[]|null
     */
    public function getFieldValueInfoList()
    {
        return $this->container['field_value_info_list'];
    }

    /**
     * Sets field_value_info_list
     *
     * @param \com\jd\openapi\apiClient\sp\product\v0\model\ViolatingProductsFieldValueInfoDTO[]|null $field_value_info_list field_value_info_list
     *
     * @return self
     */
    public function setFieldValueInfoList($field_value_info_list)
    {
        if (is_null($field_value_info_list)) {
            throw new \InvalidArgumentException('non-nullable field_value_info_list cannot be null');
        }
        $this->container['field_value_info_list'] = $field_value_info_list;

        return $this;
    }

    /**
     * Gets field_value_info_vo_list
     *
     * @return \com\jd\openapi\apiClient\sp\product\v0\model\ViolatingProductsFieldValueInfoDTO[]|null
     */
    public function getFieldValueInfoVoList()
    {
        return $this->container['field_value_info_vo_list'];
    }

    /**
     * Sets field_value_info_vo_list
     *
     * @param \com\jd\openapi\apiClient\sp\product\v0\model\ViolatingProductsFieldValueInfoDTO[]|null $field_value_info_vo_list field_value_info_vo_list
     *
     * @return self
     */
    public function setFieldValueInfoVoList($field_value_info_vo_list)
    {
        if (is_null($field_value_info_vo_list)) {
            throw new \InvalidArgumentException('non-nullable field_value_info_vo_list cannot be null');
        }
        $this->container['field_value_info_vo_list'] = $field_value_info_vo_list;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


