<?php
/**
 * AfsOrdersApi
 * PHP version 7.4
 *
 * @category Class
 * @package  com\jd\openapi\apiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */


/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace com\jd\openapi\apiClient\sp\aftercare\v0\api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use com\jd\openapi\apiClient\ApiException;
use com\jd\openapi\apiClient\Configuration;
use com\jd\openapi\apiClient\HeaderSelector;
use com\jd\openapi\apiClient\ObjectSerializer;
use com\jd\openapi\apiClient\SignatureCalculator;
/**
 * AfsOrdersApi Class Doc Comment
 *
 * @category Class
 * @package  com\jd\openapi\apiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AfsOrdersApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getAfsOrders' => [
            'application/json',
                ],
        'listAfsOrders' => [
            'application/json',
                ],
        'patchAfsOrders' => [
            'application/json',
                ],
    ];

    /**
     * @param Configuration config
     */
    public function __construct(
        $config
    ) {
        $this->client = new Client();
        $this->config = $config;
        $this->headerSelector = new HeaderSelector();
        $this->hostIndex = 0;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getAfsOrders
     *
     * @param  int $afs_order_id afs_order_id (required)
     * @param  \com\jd\openapi\apiClient\sp\aftercare\v0\model\GetAfsOrdersRequest $get_afs_orders_request get_afs_orders_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAfsOrders'] to see the possible values for this operation
     *
     * @throws \com\jd\openapi\apiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \com\jd\openapi\apiClient\sp\aftercare\v0\model\GetAfsOrdersResponse
     */
    public function getAfsOrders($afs_order_id, $get_afs_orders_request, string $contentType = self::contentTypes['getAfsOrders'][0])
    {
        list($response) = $this->getAfsOrdersWithHttpInfo($afs_order_id, $get_afs_orders_request, $contentType);
        return $response;
    }

    /**
     * Operation getAfsOrdersWithHttpInfo
     *
     * @param  int $afs_order_id (required)
     * @param  \com\jd\openapi\apiClient\sp\aftercare\v0\model\GetAfsOrdersRequest $get_afs_orders_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAfsOrders'] to see the possible values for this operation
     *
     * @throws \com\jd\openapi\apiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \com\jd\openapi\apiClient\sp\aftercare\v0\model\GetAfsOrdersResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAfsOrdersWithHttpInfo($afs_order_id, $get_afs_orders_request, string $contentType = self::contentTypes['getAfsOrders'][0])
    {
        $request = $this->getAfsOrdersRequest($afs_order_id, $get_afs_orders_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\com\jd\openapi\apiClient\sp\aftercare\v0\model\GetAfsOrdersResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\com\jd\openapi\apiClient\sp\aftercare\v0\model\GetAfsOrdersResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com\jd\openapi\apiClient\sp\aftercare\v0\model\GetAfsOrdersResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\com\jd\openapi\apiClient\sp\aftercare\v0\model\GetAfsOrdersResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com\jd\openapi\apiClient\sp\aftercare\v0\model\GetAfsOrdersResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getAfsOrdersAsync
     *
     * @param  int $afs_order_id (required)
     * @param  \com\jd\openapi\apiClient\sp\aftercare\v0\model\GetAfsOrdersRequest $get_afs_orders_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAfsOrders'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAfsOrdersAsync($afs_order_id, $get_afs_orders_request, string $contentType = self::contentTypes['getAfsOrders'][0])
    {
        return $this->getAfsOrdersAsyncWithHttpInfo($afs_order_id, $get_afs_orders_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAfsOrdersAsyncWithHttpInfo
     *
     * @param  int $afs_order_id (required)
     * @param  \com\jd\openapi\apiClient\sp\aftercare\v0\model\GetAfsOrdersRequest $get_afs_orders_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAfsOrders'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAfsOrdersAsyncWithHttpInfo($afs_order_id, $get_afs_orders_request, string $contentType = self::contentTypes['getAfsOrders'][0])
    {
        $returnType = '\com\jd\openapi\apiClient\sp\aftercare\v0\model\GetAfsOrdersResponse';
        $request = $this->getAfsOrdersRequest($afs_order_id, $get_afs_orders_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAfsOrders'
     *
     * @param  int $afs_order_id (required)
     * @param  \com\jd\openapi\apiClient\sp\aftercare\v0\model\GetAfsOrdersRequest $get_afs_orders_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAfsOrders'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getAfsOrdersRequest($afs_order_id, $get_afs_orders_request, string $contentType = self::contentTypes['getAfsOrders'][0])
    {

        // verify the required parameter 'afs_order_id' is set
        if ($afs_order_id === null || (is_array($afs_order_id) && count($afs_order_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $afs_order_id when calling getAfsOrders'
            );
        }

        // verify the required parameter 'get_afs_orders_request' is set
        if ($get_afs_orders_request === null || (is_array($get_afs_orders_request) && count($get_afs_orders_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $get_afs_orders_request when calling getAfsOrders'
            );
        }


        $resourcePath = '/sp-aftercare/v0/afs-orders/{afsOrderId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $pathParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($afs_order_id !== null) {
            $resourcePath = str_replace(
                '{' . 'afsOrderId' . '}',
                ObjectSerializer::toPathValue($afs_order_id),
                $resourcePath
            );
        }

        $pathParams['afsOrderId'] = $afs_order_id;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($get_afs_orders_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($get_afs_orders_request));
            } else {
                $httpBody = $get_afs_orders_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }



        $operationHost = $this->config->getHost();
        //get request
        $queryMethods = array("GET", "DELETE");
        if (in_array("GET", $queryMethods) && $httpBody !== null){
            $getRequestBody = json_decode($httpBody, true);
            if (json_last_error() === JSON_ERROR_NONE) {
                foreach ($getRequestBody as $key => $value) {
                    if (is_array($value)) {
                        $listValue = implode(',', array_map(function($item) {
                            return (string)$item;
                        }, $value));
                        $queryParams[$key] = $listValue;
                    } elseif (is_scalar($value)) {
                        $queryParams[$key] = (string)$value;
                    }
                }
            }

            $httpBody = null;
        }

        $query = ObjectSerializer::buildQuery($queryParams);
        // ����һ�������������洢ϵͳ����
        $systemParams = [];
        $systemParams['appKey'] = $this->config->getAppKey();
        $systemParams['appSecret'] = $this->config->getAppSecret();
        $systemParams['accessToken'] = $this->config->getAccessToken();
        $timestamp = (string)(time() * 1000); // ��ȡ��ǰʱ��������룩
        $systemParams['timestamp'] = $timestamp;

        // ����ǩ��
        $signMap = SignatureCalculator::parameterConvert($systemParams, $queryParams, $httpBody, $pathParams);
        $sign = SignatureCalculator::calculateSignature($this->config->getAppSecret(), $signMap);

        // ����ϵͳͷ��
        $headerParams["X-JOS-Sign"] =  $sign;
        $headerParams["X-JOS-Timestamp"] = $timestamp;
        $headerParams["X-JOS-App-Key"] = $this->config->getAppKey();
        $headerParams["X-JOS-Access-Token"] = $this->config->getAccessToken();
        $headerParams["X-JOS-Sdk-Version"] = "php-v2";
        if ($this->config->getRequestIdentity() !== "") {
            $headerParams["X-JOS-Request-Identity"] = $this->config->getRequestIdentity();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listAfsOrders
     *
     * @param  \com\jd\openapi\apiClient\sp\aftercare\v0\model\ListAfsOrdersRequest $list_afs_orders_request list_afs_orders_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listAfsOrders'] to see the possible values for this operation
     *
     * @throws \com\jd\openapi\apiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \com\jd\openapi\apiClient\sp\aftercare\v0\model\ListAfsOrdersResponse
     */
    public function listAfsOrders($list_afs_orders_request, string $contentType = self::contentTypes['listAfsOrders'][0])
    {
        list($response) = $this->listAfsOrdersWithHttpInfo($list_afs_orders_request, $contentType);
        return $response;
    }

    /**
     * Operation listAfsOrdersWithHttpInfo
     *
     * @param  \com\jd\openapi\apiClient\sp\aftercare\v0\model\ListAfsOrdersRequest $list_afs_orders_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listAfsOrders'] to see the possible values for this operation
     *
     * @throws \com\jd\openapi\apiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \com\jd\openapi\apiClient\sp\aftercare\v0\model\ListAfsOrdersResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function listAfsOrdersWithHttpInfo($list_afs_orders_request, string $contentType = self::contentTypes['listAfsOrders'][0])
    {
        $request = $this->listAfsOrdersRequest($list_afs_orders_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\com\jd\openapi\apiClient\sp\aftercare\v0\model\ListAfsOrdersResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\com\jd\openapi\apiClient\sp\aftercare\v0\model\ListAfsOrdersResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com\jd\openapi\apiClient\sp\aftercare\v0\model\ListAfsOrdersResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\com\jd\openapi\apiClient\sp\aftercare\v0\model\ListAfsOrdersResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com\jd\openapi\apiClient\sp\aftercare\v0\model\ListAfsOrdersResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation listAfsOrdersAsync
     *
     * @param  \com\jd\openapi\apiClient\sp\aftercare\v0\model\ListAfsOrdersRequest $list_afs_orders_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listAfsOrders'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listAfsOrdersAsync($list_afs_orders_request, string $contentType = self::contentTypes['listAfsOrders'][0])
    {
        return $this->listAfsOrdersAsyncWithHttpInfo($list_afs_orders_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listAfsOrdersAsyncWithHttpInfo
     *
     * @param  \com\jd\openapi\apiClient\sp\aftercare\v0\model\ListAfsOrdersRequest $list_afs_orders_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listAfsOrders'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listAfsOrdersAsyncWithHttpInfo($list_afs_orders_request, string $contentType = self::contentTypes['listAfsOrders'][0])
    {
        $returnType = '\com\jd\openapi\apiClient\sp\aftercare\v0\model\ListAfsOrdersResponse';
        $request = $this->listAfsOrdersRequest($list_afs_orders_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listAfsOrders'
     *
     * @param  \com\jd\openapi\apiClient\sp\aftercare\v0\model\ListAfsOrdersRequest $list_afs_orders_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listAfsOrders'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listAfsOrdersRequest($list_afs_orders_request, string $contentType = self::contentTypes['listAfsOrders'][0])
    {

        // verify the required parameter 'list_afs_orders_request' is set
        if ($list_afs_orders_request === null || (is_array($list_afs_orders_request) && count($list_afs_orders_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $list_afs_orders_request when calling listAfsOrders'
            );
        }


        $resourcePath = '/sp-aftercare/v0/afs-orders';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $pathParams = [];
        $httpBody = '';
        $multipart = false;




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($list_afs_orders_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($list_afs_orders_request));
            } else {
                $httpBody = $list_afs_orders_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }



        $operationHost = $this->config->getHost();
        //get request
        $queryMethods = array("GET", "DELETE");
        if (in_array("GET", $queryMethods) && $httpBody !== null){
            $getRequestBody = json_decode($httpBody, true);
            if (json_last_error() === JSON_ERROR_NONE) {
                foreach ($getRequestBody as $key => $value) {
                    if (is_array($value)) {
                        $listValue = implode(',', array_map(function($item) {
                            return (string)$item;
                        }, $value));
                        $queryParams[$key] = $listValue;
                    } elseif (is_scalar($value)) {
                        $queryParams[$key] = (string)$value;
                    }
                }
            }

            $httpBody = null;
        }

        $query = ObjectSerializer::buildQuery($queryParams);
        // ����һ�������������洢ϵͳ����
        $systemParams = [];
        $systemParams['appKey'] = $this->config->getAppKey();
        $systemParams['appSecret'] = $this->config->getAppSecret();
        $systemParams['accessToken'] = $this->config->getAccessToken();
        $timestamp = (string)(time() * 1000); // ��ȡ��ǰʱ��������룩
        $systemParams['timestamp'] = $timestamp;

        // ����ǩ��
        $signMap = SignatureCalculator::parameterConvert($systemParams, $queryParams, $httpBody, $pathParams);
        $sign = SignatureCalculator::calculateSignature($this->config->getAppSecret(), $signMap);

        // ����ϵͳͷ��
        $headerParams["X-JOS-Sign"] =  $sign;
        $headerParams["X-JOS-Timestamp"] = $timestamp;
        $headerParams["X-JOS-App-Key"] = $this->config->getAppKey();
        $headerParams["X-JOS-Access-Token"] = $this->config->getAccessToken();
        $headerParams["X-JOS-Sdk-Version"] = "php-v2";
        if ($this->config->getRequestIdentity() !== "") {
            $headerParams["X-JOS-Request-Identity"] = $this->config->getRequestIdentity();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation patchAfsOrders
     *
     * @param  int $afs_order_id afs_order_id (required)
     * @param  \com\jd\openapi\apiClient\sp\aftercare\v0\model\PatchAfsOrdersRequest $patch_afs_orders_request patch_afs_orders_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchAfsOrders'] to see the possible values for this operation
     *
     * @throws \com\jd\openapi\apiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \com\jd\openapi\apiClient\sp\aftercare\v0\model\PatchAfsOrdersResponse
     */
    public function patchAfsOrders($afs_order_id, $patch_afs_orders_request, string $contentType = self::contentTypes['patchAfsOrders'][0])
    {
        list($response) = $this->patchAfsOrdersWithHttpInfo($afs_order_id, $patch_afs_orders_request, $contentType);
        return $response;
    }

    /**
     * Operation patchAfsOrdersWithHttpInfo
     *
     * @param  int $afs_order_id (required)
     * @param  \com\jd\openapi\apiClient\sp\aftercare\v0\model\PatchAfsOrdersRequest $patch_afs_orders_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchAfsOrders'] to see the possible values for this operation
     *
     * @throws \com\jd\openapi\apiClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \com\jd\openapi\apiClient\sp\aftercare\v0\model\PatchAfsOrdersResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function patchAfsOrdersWithHttpInfo($afs_order_id, $patch_afs_orders_request, string $contentType = self::contentTypes['patchAfsOrders'][0])
    {
        $request = $this->patchAfsOrdersRequest($afs_order_id, $patch_afs_orders_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\com\jd\openapi\apiClient\sp\aftercare\v0\model\PatchAfsOrdersResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\com\jd\openapi\apiClient\sp\aftercare\v0\model\PatchAfsOrdersResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com\jd\openapi\apiClient\sp\aftercare\v0\model\PatchAfsOrdersResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\com\jd\openapi\apiClient\sp\aftercare\v0\model\PatchAfsOrdersResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com\jd\openapi\apiClient\sp\aftercare\v0\model\PatchAfsOrdersResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation patchAfsOrdersAsync
     *
     * @param  int $afs_order_id (required)
     * @param  \com\jd\openapi\apiClient\sp\aftercare\v0\model\PatchAfsOrdersRequest $patch_afs_orders_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchAfsOrders'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function patchAfsOrdersAsync($afs_order_id, $patch_afs_orders_request, string $contentType = self::contentTypes['patchAfsOrders'][0])
    {
        return $this->patchAfsOrdersAsyncWithHttpInfo($afs_order_id, $patch_afs_orders_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation patchAfsOrdersAsyncWithHttpInfo
     *
     * @param  int $afs_order_id (required)
     * @param  \com\jd\openapi\apiClient\sp\aftercare\v0\model\PatchAfsOrdersRequest $patch_afs_orders_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchAfsOrders'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function patchAfsOrdersAsyncWithHttpInfo($afs_order_id, $patch_afs_orders_request, string $contentType = self::contentTypes['patchAfsOrders'][0])
    {
        $returnType = '\com\jd\openapi\apiClient\sp\aftercare\v0\model\PatchAfsOrdersResponse';
        $request = $this->patchAfsOrdersRequest($afs_order_id, $patch_afs_orders_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'patchAfsOrders'
     *
     * @param  int $afs_order_id (required)
     * @param  \com\jd\openapi\apiClient\sp\aftercare\v0\model\PatchAfsOrdersRequest $patch_afs_orders_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['patchAfsOrders'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function patchAfsOrdersRequest($afs_order_id, $patch_afs_orders_request, string $contentType = self::contentTypes['patchAfsOrders'][0])
    {

        // verify the required parameter 'afs_order_id' is set
        if ($afs_order_id === null || (is_array($afs_order_id) && count($afs_order_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $afs_order_id when calling patchAfsOrders'
            );
        }

        // verify the required parameter 'patch_afs_orders_request' is set
        if ($patch_afs_orders_request === null || (is_array($patch_afs_orders_request) && count($patch_afs_orders_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $patch_afs_orders_request when calling patchAfsOrders'
            );
        }


        $resourcePath = '/sp-aftercare/v0/afs-orders/{afsOrderId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $pathParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($afs_order_id !== null) {
            $resourcePath = str_replace(
                '{' . 'afsOrderId' . '}',
                ObjectSerializer::toPathValue($afs_order_id),
                $resourcePath
            );
        }

        $pathParams['afsOrderId'] = $afs_order_id;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($patch_afs_orders_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($patch_afs_orders_request));
            } else {
                $httpBody = $patch_afs_orders_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }



        $operationHost = $this->config->getHost();
        //get request
        $queryMethods = array("GET", "DELETE");
        if (in_array("PATCH", $queryMethods) && $httpBody !== null){
            $getRequestBody = json_decode($httpBody, true);
            if (json_last_error() === JSON_ERROR_NONE) {
                foreach ($getRequestBody as $key => $value) {
                    if (is_array($value)) {
                        $listValue = implode(',', array_map(function($item) {
                            return (string)$item;
                        }, $value));
                        $queryParams[$key] = $listValue;
                    } elseif (is_scalar($value)) {
                        $queryParams[$key] = (string)$value;
                    }
                }
            }

            $httpBody = null;
        }

        $query = ObjectSerializer::buildQuery($queryParams);
        // ����һ�������������洢ϵͳ����
        $systemParams = [];
        $systemParams['appKey'] = $this->config->getAppKey();
        $systemParams['appSecret'] = $this->config->getAppSecret();
        $systemParams['accessToken'] = $this->config->getAccessToken();
        $timestamp = (string)(time() * 1000); // ��ȡ��ǰʱ��������룩
        $systemParams['timestamp'] = $timestamp;

        // ����ǩ��
        $signMap = SignatureCalculator::parameterConvert($systemParams, $queryParams, $httpBody, $pathParams);
        $sign = SignatureCalculator::calculateSignature($this->config->getAppSecret(), $signMap);

        // ����ϵͳͷ��
        $headerParams["X-JOS-Sign"] =  $sign;
        $headerParams["X-JOS-Timestamp"] = $timestamp;
        $headerParams["X-JOS-App-Key"] = $this->config->getAppKey();
        $headerParams["X-JOS-Access-Token"] = $this->config->getAccessToken();
        $headerParams["X-JOS-Sdk-Version"] = "php-v2";
        if ($this->config->getRequestIdentity() !== "") {
            $headerParams["X-JOS-Request-Identity"] = $this->config->getRequestIdentity();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );
        return new Request(
            'PATCH',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
