<?php
/**
 * InvoiceApplicationsInvoiceApplicationDTO
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  com\jd\openapi\apiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */


/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace com\jd\openapi\apiClient\sp\finance\v0\model;

use \ArrayAccess;
use \com\jd\openapi\apiClient\ObjectSerializer;

/**
 * InvoiceApplicationsInvoiceApplicationDTO Class Doc Comment
 *
 * @category Class
 * @package  com\jd\openapi\apiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class InvoiceApplicationsInvoiceApplicationDTO implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'InvoiceApplicationsInvoiceApplicationDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'source_id' => 'int',
        'invoice_type_name' => 'string',
        'logistics_receiver_address' => 'string',
        'order_id' => 'int',
        'invoice_content_type' => 'int',
        'vender_id' => 'int',
        'consumer_phone' => 'string',
        'invoice_amount' => 'float',
        'apply_id' => 'int',
        'order_complete_time' => 'int',
        'reject_reason' => 'string',
        'should_invoice_amount' => 'float',
        'invoice_title_type' => 'int',
        'consumer_tax_id' => 'string',
        'invoice_content_name' => 'string',
        'customer_email' => 'string',
        'invoice_type' => 'int',
        'apply_time' => 'int',
        'invoice_title' => 'string',
        'consumer_address' => 'string',
        'logistics_receiver_name' => 'string',
        'consumer_bank_account' => 'string',
        'logistics_receiver_phone' => 'string',
        'audit_time' => 'int',
        'invoice_status' => 'int',
        'consumer_bank_name' => 'string',
        'order_should_invoice_amount_detail_list' => '\com\jd\openapi\apiClient\sp\finance\v0\model\InvoiceApplicationsOrderShouldInvoiceAmountDTO[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'source_id' => 'int32',
        'invoice_type_name' => null,
        'logistics_receiver_address' => null,
        'order_id' => 'int64',
        'invoice_content_type' => 'int32',
        'vender_id' => 'int64',
        'consumer_phone' => null,
        'invoice_amount' => 'decimal',
        'apply_id' => 'int64',
        'order_complete_time' => 'int64',
        'reject_reason' => null,
        'should_invoice_amount' => 'decimal',
        'invoice_title_type' => 'int32',
        'consumer_tax_id' => null,
        'invoice_content_name' => null,
        'customer_email' => null,
        'invoice_type' => 'int32',
        'apply_time' => 'int64',
        'invoice_title' => null,
        'consumer_address' => null,
        'logistics_receiver_name' => null,
        'consumer_bank_account' => null,
        'logistics_receiver_phone' => null,
        'audit_time' => 'int64',
        'invoice_status' => 'int32',
        'consumer_bank_name' => null,
        'order_should_invoice_amount_detail_list' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'source_id' => true,
		'invoice_type_name' => true,
		'logistics_receiver_address' => true,
		'order_id' => true,
		'invoice_content_type' => true,
		'vender_id' => true,
		'consumer_phone' => true,
		'invoice_amount' => true,
		'apply_id' => true,
		'order_complete_time' => true,
		'reject_reason' => true,
		'should_invoice_amount' => true,
		'invoice_title_type' => true,
		'consumer_tax_id' => true,
		'invoice_content_name' => true,
		'customer_email' => true,
		'invoice_type' => true,
		'apply_time' => true,
		'invoice_title' => true,
		'consumer_address' => true,
		'logistics_receiver_name' => true,
		'consumer_bank_account' => true,
		'logistics_receiver_phone' => true,
		'audit_time' => true,
		'invoice_status' => true,
		'consumer_bank_name' => true,
		'order_should_invoice_amount_detail_list' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'source_id' => 'sourceId',
        'invoice_type_name' => 'invoiceTypeName',
        'logistics_receiver_address' => 'logisticsReceiverAddress',
        'order_id' => 'orderId',
        'invoice_content_type' => 'invoiceContentType',
        'vender_id' => 'venderId',
        'consumer_phone' => 'consumerPhone',
        'invoice_amount' => 'invoiceAmount',
        'apply_id' => 'applyId',
        'order_complete_time' => 'orderCompleteTime',
        'reject_reason' => 'rejectReason',
        'should_invoice_amount' => 'shouldInvoiceAmount',
        'invoice_title_type' => 'invoiceTitleType',
        'consumer_tax_id' => 'consumerTaxId',
        'invoice_content_name' => 'invoiceContentName',
        'customer_email' => 'customerEmail',
        'invoice_type' => 'invoiceType',
        'apply_time' => 'applyTime',
        'invoice_title' => 'invoiceTitle',
        'consumer_address' => 'consumerAddress',
        'logistics_receiver_name' => 'logisticsReceiverName',
        'consumer_bank_account' => 'consumerBankAccount',
        'logistics_receiver_phone' => 'logisticsReceiverPhone',
        'audit_time' => 'auditTime',
        'invoice_status' => 'invoiceStatus',
        'consumer_bank_name' => 'consumerBankName',
        'order_should_invoice_amount_detail_list' => 'orderShouldInvoiceAmountDetailList'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'source_id' => 'setSourceId',
        'invoice_type_name' => 'setInvoiceTypeName',
        'logistics_receiver_address' => 'setLogisticsReceiverAddress',
        'order_id' => 'setOrderId',
        'invoice_content_type' => 'setInvoiceContentType',
        'vender_id' => 'setVenderId',
        'consumer_phone' => 'setConsumerPhone',
        'invoice_amount' => 'setInvoiceAmount',
        'apply_id' => 'setApplyId',
        'order_complete_time' => 'setOrderCompleteTime',
        'reject_reason' => 'setRejectReason',
        'should_invoice_amount' => 'setShouldInvoiceAmount',
        'invoice_title_type' => 'setInvoiceTitleType',
        'consumer_tax_id' => 'setConsumerTaxId',
        'invoice_content_name' => 'setInvoiceContentName',
        'customer_email' => 'setCustomerEmail',
        'invoice_type' => 'setInvoiceType',
        'apply_time' => 'setApplyTime',
        'invoice_title' => 'setInvoiceTitle',
        'consumer_address' => 'setConsumerAddress',
        'logistics_receiver_name' => 'setLogisticsReceiverName',
        'consumer_bank_account' => 'setConsumerBankAccount',
        'logistics_receiver_phone' => 'setLogisticsReceiverPhone',
        'audit_time' => 'setAuditTime',
        'invoice_status' => 'setInvoiceStatus',
        'consumer_bank_name' => 'setConsumerBankName',
        'order_should_invoice_amount_detail_list' => 'setOrderShouldInvoiceAmountDetailList'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'source_id' => 'getSourceId',
        'invoice_type_name' => 'getInvoiceTypeName',
        'logistics_receiver_address' => 'getLogisticsReceiverAddress',
        'order_id' => 'getOrderId',
        'invoice_content_type' => 'getInvoiceContentType',
        'vender_id' => 'getVenderId',
        'consumer_phone' => 'getConsumerPhone',
        'invoice_amount' => 'getInvoiceAmount',
        'apply_id' => 'getApplyId',
        'order_complete_time' => 'getOrderCompleteTime',
        'reject_reason' => 'getRejectReason',
        'should_invoice_amount' => 'getShouldInvoiceAmount',
        'invoice_title_type' => 'getInvoiceTitleType',
        'consumer_tax_id' => 'getConsumerTaxId',
        'invoice_content_name' => 'getInvoiceContentName',
        'customer_email' => 'getCustomerEmail',
        'invoice_type' => 'getInvoiceType',
        'apply_time' => 'getApplyTime',
        'invoice_title' => 'getInvoiceTitle',
        'consumer_address' => 'getConsumerAddress',
        'logistics_receiver_name' => 'getLogisticsReceiverName',
        'consumer_bank_account' => 'getConsumerBankAccount',
        'logistics_receiver_phone' => 'getLogisticsReceiverPhone',
        'audit_time' => 'getAuditTime',
        'invoice_status' => 'getInvoiceStatus',
        'consumer_bank_name' => 'getConsumerBankName',
        'order_should_invoice_amount_detail_list' => 'getOrderShouldInvoiceAmountDetailList'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('source_id', $data ?? [], null);
        $this->setIfExists('invoice_type_name', $data ?? [], null);
        $this->setIfExists('logistics_receiver_address', $data ?? [], null);
        $this->setIfExists('order_id', $data ?? [], null);
        $this->setIfExists('invoice_content_type', $data ?? [], null);
        $this->setIfExists('vender_id', $data ?? [], null);
        $this->setIfExists('consumer_phone', $data ?? [], null);
        $this->setIfExists('invoice_amount', $data ?? [], null);
        $this->setIfExists('apply_id', $data ?? [], null);
        $this->setIfExists('order_complete_time', $data ?? [], null);
        $this->setIfExists('reject_reason', $data ?? [], null);
        $this->setIfExists('should_invoice_amount', $data ?? [], null);
        $this->setIfExists('invoice_title_type', $data ?? [], null);
        $this->setIfExists('consumer_tax_id', $data ?? [], null);
        $this->setIfExists('invoice_content_name', $data ?? [], null);
        $this->setIfExists('customer_email', $data ?? [], null);
        $this->setIfExists('invoice_type', $data ?? [], null);
        $this->setIfExists('apply_time', $data ?? [], null);
        $this->setIfExists('invoice_title', $data ?? [], null);
        $this->setIfExists('consumer_address', $data ?? [], null);
        $this->setIfExists('logistics_receiver_name', $data ?? [], null);
        $this->setIfExists('consumer_bank_account', $data ?? [], null);
        $this->setIfExists('logistics_receiver_phone', $data ?? [], null);
        $this->setIfExists('audit_time', $data ?? [], null);
        $this->setIfExists('invoice_status', $data ?? [], null);
        $this->setIfExists('consumer_bank_name', $data ?? [], null);
        $this->setIfExists('order_should_invoice_amount_detail_list', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets source_id
     *
     * @return int|null
     */
    public function getSourceId()
    {
        return $this->container['source_id'];
    }

    /**
     * Sets source_id
     *
     * @param int|null $source_id source_id
     *
     * @return self
     */
    public function setSourceId($source_id)
    {
        if (is_null($source_id)) {
            array_push($this->openAPINullablesSetToNull, 'source_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('source_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['source_id'] = $source_id;

        return $this;
    }

    /**
     * Gets invoice_type_name
     *
     * @return string|null
     */
    public function getInvoiceTypeName()
    {
        return $this->container['invoice_type_name'];
    }

    /**
     * Sets invoice_type_name
     *
     * @param string|null $invoice_type_name invoice_type_name
     *
     * @return self
     */
    public function setInvoiceTypeName($invoice_type_name)
    {
        if (is_null($invoice_type_name)) {
            array_push($this->openAPINullablesSetToNull, 'invoice_type_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('invoice_type_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['invoice_type_name'] = $invoice_type_name;

        return $this;
    }

    /**
     * Gets logistics_receiver_address
     *
     * @return string|null
     */
    public function getLogisticsReceiverAddress()
    {
        return $this->container['logistics_receiver_address'];
    }

    /**
     * Sets logistics_receiver_address
     *
     * @param string|null $logistics_receiver_address logistics_receiver_address
     *
     * @return self
     */
    public function setLogisticsReceiverAddress($logistics_receiver_address)
    {
        if (is_null($logistics_receiver_address)) {
            array_push($this->openAPINullablesSetToNull, 'logistics_receiver_address');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('logistics_receiver_address', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['logistics_receiver_address'] = $logistics_receiver_address;

        return $this;
    }

    /**
     * Gets order_id
     *
     * @return int|null
     */
    public function getOrderId()
    {
        return $this->container['order_id'];
    }

    /**
     * Sets order_id
     *
     * @param int|null $order_id order_id
     *
     * @return self
     */
    public function setOrderId($order_id)
    {
        if (is_null($order_id)) {
            array_push($this->openAPINullablesSetToNull, 'order_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('order_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['order_id'] = $order_id;

        return $this;
    }

    /**
     * Gets invoice_content_type
     *
     * @return int|null
     */
    public function getInvoiceContentType()
    {
        return $this->container['invoice_content_type'];
    }

    /**
     * Sets invoice_content_type
     *
     * @param int|null $invoice_content_type invoice_content_type
     *
     * @return self
     */
    public function setInvoiceContentType($invoice_content_type)
    {
        if (is_null($invoice_content_type)) {
            array_push($this->openAPINullablesSetToNull, 'invoice_content_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('invoice_content_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['invoice_content_type'] = $invoice_content_type;

        return $this;
    }

    /**
     * Gets vender_id
     *
     * @return int|null
     */
    public function getVenderId()
    {
        return $this->container['vender_id'];
    }

    /**
     * Sets vender_id
     *
     * @param int|null $vender_id vender_id
     *
     * @return self
     */
    public function setVenderId($vender_id)
    {
        if (is_null($vender_id)) {
            array_push($this->openAPINullablesSetToNull, 'vender_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('vender_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['vender_id'] = $vender_id;

        return $this;
    }

    /**
     * Gets consumer_phone
     *
     * @return string|null
     */
    public function getConsumerPhone()
    {
        return $this->container['consumer_phone'];
    }

    /**
     * Sets consumer_phone
     *
     * @param string|null $consumer_phone consumer_phone
     *
     * @return self
     */
    public function setConsumerPhone($consumer_phone)
    {
        if (is_null($consumer_phone)) {
            array_push($this->openAPINullablesSetToNull, 'consumer_phone');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('consumer_phone', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['consumer_phone'] = $consumer_phone;

        return $this;
    }

    /**
     * Gets invoice_amount
     *
     * @return float|null
     */
    public function getInvoiceAmount()
    {
        return $this->container['invoice_amount'];
    }

    /**
     * Sets invoice_amount
     *
     * @param float|null $invoice_amount invoice_amount
     *
     * @return self
     */
    public function setInvoiceAmount($invoice_amount)
    {
        if (is_null($invoice_amount)) {
            array_push($this->openAPINullablesSetToNull, 'invoice_amount');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('invoice_amount', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['invoice_amount'] = $invoice_amount;

        return $this;
    }

    /**
     * Gets apply_id
     *
     * @return int|null
     */
    public function getApplyId()
    {
        return $this->container['apply_id'];
    }

    /**
     * Sets apply_id
     *
     * @param int|null $apply_id apply_id
     *
     * @return self
     */
    public function setApplyId($apply_id)
    {
        if (is_null($apply_id)) {
            array_push($this->openAPINullablesSetToNull, 'apply_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('apply_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['apply_id'] = $apply_id;

        return $this;
    }

    /**
     * Gets order_complete_time
     *
     * @return int|null
     */
    public function getOrderCompleteTime()
    {
        return $this->container['order_complete_time'];
    }

    /**
     * Sets order_complete_time
     *
     * @param int|null $order_complete_time order_complete_time
     *
     * @return self
     */
    public function setOrderCompleteTime($order_complete_time)
    {
        if (is_null($order_complete_time)) {
            array_push($this->openAPINullablesSetToNull, 'order_complete_time');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('order_complete_time', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['order_complete_time'] = $order_complete_time;

        return $this;
    }

    /**
     * Gets reject_reason
     *
     * @return string|null
     */
    public function getRejectReason()
    {
        return $this->container['reject_reason'];
    }

    /**
     * Sets reject_reason
     *
     * @param string|null $reject_reason reject_reason
     *
     * @return self
     */
    public function setRejectReason($reject_reason)
    {
        if (is_null($reject_reason)) {
            array_push($this->openAPINullablesSetToNull, 'reject_reason');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('reject_reason', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['reject_reason'] = $reject_reason;

        return $this;
    }

    /**
     * Gets should_invoice_amount
     *
     * @return float|null
     */
    public function getShouldInvoiceAmount()
    {
        return $this->container['should_invoice_amount'];
    }

    /**
     * Sets should_invoice_amount
     *
     * @param float|null $should_invoice_amount should_invoice_amount
     *
     * @return self
     */
    public function setShouldInvoiceAmount($should_invoice_amount)
    {
        if (is_null($should_invoice_amount)) {
            array_push($this->openAPINullablesSetToNull, 'should_invoice_amount');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('should_invoice_amount', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['should_invoice_amount'] = $should_invoice_amount;

        return $this;
    }

    /**
     * Gets invoice_title_type
     *
     * @return int|null
     */
    public function getInvoiceTitleType()
    {
        return $this->container['invoice_title_type'];
    }

    /**
     * Sets invoice_title_type
     *
     * @param int|null $invoice_title_type invoice_title_type
     *
     * @return self
     */
    public function setInvoiceTitleType($invoice_title_type)
    {
        if (is_null($invoice_title_type)) {
            array_push($this->openAPINullablesSetToNull, 'invoice_title_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('invoice_title_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['invoice_title_type'] = $invoice_title_type;

        return $this;
    }

    /**
     * Gets consumer_tax_id
     *
     * @return string|null
     */
    public function getConsumerTaxId()
    {
        return $this->container['consumer_tax_id'];
    }

    /**
     * Sets consumer_tax_id
     *
     * @param string|null $consumer_tax_id consumer_tax_id
     *
     * @return self
     */
    public function setConsumerTaxId($consumer_tax_id)
    {
        if (is_null($consumer_tax_id)) {
            array_push($this->openAPINullablesSetToNull, 'consumer_tax_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('consumer_tax_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['consumer_tax_id'] = $consumer_tax_id;

        return $this;
    }

    /**
     * Gets invoice_content_name
     *
     * @return string|null
     */
    public function getInvoiceContentName()
    {
        return $this->container['invoice_content_name'];
    }

    /**
     * Sets invoice_content_name
     *
     * @param string|null $invoice_content_name invoice_content_name
     *
     * @return self
     */
    public function setInvoiceContentName($invoice_content_name)
    {
        if (is_null($invoice_content_name)) {
            array_push($this->openAPINullablesSetToNull, 'invoice_content_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('invoice_content_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['invoice_content_name'] = $invoice_content_name;

        return $this;
    }

    /**
     * Gets customer_email
     *
     * @return string|null
     */
    public function getCustomerEmail()
    {
        return $this->container['customer_email'];
    }

    /**
     * Sets customer_email
     *
     * @param string|null $customer_email customer_email
     *
     * @return self
     */
    public function setCustomerEmail($customer_email)
    {
        if (is_null($customer_email)) {
            array_push($this->openAPINullablesSetToNull, 'customer_email');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('customer_email', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['customer_email'] = $customer_email;

        return $this;
    }

    /**
     * Gets invoice_type
     *
     * @return int|null
     */
    public function getInvoiceType()
    {
        return $this->container['invoice_type'];
    }

    /**
     * Sets invoice_type
     *
     * @param int|null $invoice_type invoice_type
     *
     * @return self
     */
    public function setInvoiceType($invoice_type)
    {
        if (is_null($invoice_type)) {
            array_push($this->openAPINullablesSetToNull, 'invoice_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('invoice_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['invoice_type'] = $invoice_type;

        return $this;
    }

    /**
     * Gets apply_time
     *
     * @return int|null
     */
    public function getApplyTime()
    {
        return $this->container['apply_time'];
    }

    /**
     * Sets apply_time
     *
     * @param int|null $apply_time apply_time
     *
     * @return self
     */
    public function setApplyTime($apply_time)
    {
        if (is_null($apply_time)) {
            array_push($this->openAPINullablesSetToNull, 'apply_time');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('apply_time', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['apply_time'] = $apply_time;

        return $this;
    }

    /**
     * Gets invoice_title
     *
     * @return string|null
     */
    public function getInvoiceTitle()
    {
        return $this->container['invoice_title'];
    }

    /**
     * Sets invoice_title
     *
     * @param string|null $invoice_title invoice_title
     *
     * @return self
     */
    public function setInvoiceTitle($invoice_title)
    {
        if (is_null($invoice_title)) {
            array_push($this->openAPINullablesSetToNull, 'invoice_title');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('invoice_title', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['invoice_title'] = $invoice_title;

        return $this;
    }

    /**
     * Gets consumer_address
     *
     * @return string|null
     */
    public function getConsumerAddress()
    {
        return $this->container['consumer_address'];
    }

    /**
     * Sets consumer_address
     *
     * @param string|null $consumer_address consumer_address
     *
     * @return self
     */
    public function setConsumerAddress($consumer_address)
    {
        if (is_null($consumer_address)) {
            array_push($this->openAPINullablesSetToNull, 'consumer_address');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('consumer_address', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['consumer_address'] = $consumer_address;

        return $this;
    }

    /**
     * Gets logistics_receiver_name
     *
     * @return string|null
     */
    public function getLogisticsReceiverName()
    {
        return $this->container['logistics_receiver_name'];
    }

    /**
     * Sets logistics_receiver_name
     *
     * @param string|null $logistics_receiver_name logistics_receiver_name
     *
     * @return self
     */
    public function setLogisticsReceiverName($logistics_receiver_name)
    {
        if (is_null($logistics_receiver_name)) {
            array_push($this->openAPINullablesSetToNull, 'logistics_receiver_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('logistics_receiver_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['logistics_receiver_name'] = $logistics_receiver_name;

        return $this;
    }

    /**
     * Gets consumer_bank_account
     *
     * @return string|null
     */
    public function getConsumerBankAccount()
    {
        return $this->container['consumer_bank_account'];
    }

    /**
     * Sets consumer_bank_account
     *
     * @param string|null $consumer_bank_account consumer_bank_account
     *
     * @return self
     */
    public function setConsumerBankAccount($consumer_bank_account)
    {
        if (is_null($consumer_bank_account)) {
            array_push($this->openAPINullablesSetToNull, 'consumer_bank_account');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('consumer_bank_account', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['consumer_bank_account'] = $consumer_bank_account;

        return $this;
    }

    /**
     * Gets logistics_receiver_phone
     *
     * @return string|null
     */
    public function getLogisticsReceiverPhone()
    {
        return $this->container['logistics_receiver_phone'];
    }

    /**
     * Sets logistics_receiver_phone
     *
     * @param string|null $logistics_receiver_phone logistics_receiver_phone
     *
     * @return self
     */
    public function setLogisticsReceiverPhone($logistics_receiver_phone)
    {
        if (is_null($logistics_receiver_phone)) {
            array_push($this->openAPINullablesSetToNull, 'logistics_receiver_phone');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('logistics_receiver_phone', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['logistics_receiver_phone'] = $logistics_receiver_phone;

        return $this;
    }

    /**
     * Gets audit_time
     *
     * @return int|null
     */
    public function getAuditTime()
    {
        return $this->container['audit_time'];
    }

    /**
     * Sets audit_time
     *
     * @param int|null $audit_time audit_time
     *
     * @return self
     */
    public function setAuditTime($audit_time)
    {
        if (is_null($audit_time)) {
            array_push($this->openAPINullablesSetToNull, 'audit_time');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('audit_time', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['audit_time'] = $audit_time;

        return $this;
    }

    /**
     * Gets invoice_status
     *
     * @return int|null
     */
    public function getInvoiceStatus()
    {
        return $this->container['invoice_status'];
    }

    /**
     * Sets invoice_status
     *
     * @param int|null $invoice_status invoice_status
     *
     * @return self
     */
    public function setInvoiceStatus($invoice_status)
    {
        if (is_null($invoice_status)) {
            array_push($this->openAPINullablesSetToNull, 'invoice_status');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('invoice_status', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['invoice_status'] = $invoice_status;

        return $this;
    }

    /**
     * Gets consumer_bank_name
     *
     * @return string|null
     */
    public function getConsumerBankName()
    {
        return $this->container['consumer_bank_name'];
    }

    /**
     * Sets consumer_bank_name
     *
     * @param string|null $consumer_bank_name consumer_bank_name
     *
     * @return self
     */
    public function setConsumerBankName($consumer_bank_name)
    {
        if (is_null($consumer_bank_name)) {
            array_push($this->openAPINullablesSetToNull, 'consumer_bank_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('consumer_bank_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['consumer_bank_name'] = $consumer_bank_name;

        return $this;
    }

    /**
     * Gets order_should_invoice_amount_detail_list
     *
     * @return \com\jd\openapi\apiClient\sp\finance\v0\model\InvoiceApplicationsOrderShouldInvoiceAmountDTO[]|null
     */
    public function getOrderShouldInvoiceAmountDetailList()
    {
        return $this->container['order_should_invoice_amount_detail_list'];
    }

    /**
     * Sets order_should_invoice_amount_detail_list
     *
     * @param \com\jd\openapi\apiClient\sp\finance\v0\model\InvoiceApplicationsOrderShouldInvoiceAmountDTO[]|null $order_should_invoice_amount_detail_list order_should_invoice_amount_detail_list
     *
     * @return self
     */
    public function setOrderShouldInvoiceAmountDetailList($order_should_invoice_amount_detail_list)
    {
        if (is_null($order_should_invoice_amount_detail_list)) {
            throw new \InvalidArgumentException('non-nullable order_should_invoice_amount_detail_list cannot be null');
        }
        $this->container['order_should_invoice_amount_detail_list'] = $order_should_invoice_amount_detail_list;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


