<?php
/**
 * AfsOrdersQuestionInfoDTO
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  com\jd\openapi\apiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */


/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace com\jd\openapi\apiClient\sp\aftercare\v0\model;

use \ArrayAccess;
use \com\jd\openapi\apiClient\ObjectSerializer;

/**
 * AfsOrdersQuestionInfoDTO Class Doc Comment
 *
 * @category Class
 * @package  com\jd\openapi\apiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AfsOrdersQuestionInfoDTO implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AfsOrdersQuestionInfoDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'question_desc' => 'string',
        'question_video_image' => 'string',
        'question_type_second_cid' => 'int',
        'question_video' => 'string',
        'question_type_second_cid_desc' => 'string',
        'question_pic' => 'string',
        'question_type_first_cid' => 'int',
        'question_type_first_cid_desc' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'question_desc' => null,
        'question_video_image' => null,
        'question_type_second_cid' => 'int32',
        'question_video' => null,
        'question_type_second_cid_desc' => null,
        'question_pic' => null,
        'question_type_first_cid' => 'int32',
        'question_type_first_cid_desc' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'question_desc' => true,
		'question_video_image' => true,
		'question_type_second_cid' => true,
		'question_video' => true,
		'question_type_second_cid_desc' => true,
		'question_pic' => true,
		'question_type_first_cid' => true,
		'question_type_first_cid_desc' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'question_desc' => 'questionDesc',
        'question_video_image' => 'questionVideoImage',
        'question_type_second_cid' => 'questionTypeSecondCid',
        'question_video' => 'questionVideo',
        'question_type_second_cid_desc' => 'questionTypeSecondCidDesc',
        'question_pic' => 'questionPic',
        'question_type_first_cid' => 'questionTypeFirstCid',
        'question_type_first_cid_desc' => 'questionTypeFirstCidDesc'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'question_desc' => 'setQuestionDesc',
        'question_video_image' => 'setQuestionVideoImage',
        'question_type_second_cid' => 'setQuestionTypeSecondCid',
        'question_video' => 'setQuestionVideo',
        'question_type_second_cid_desc' => 'setQuestionTypeSecondCidDesc',
        'question_pic' => 'setQuestionPic',
        'question_type_first_cid' => 'setQuestionTypeFirstCid',
        'question_type_first_cid_desc' => 'setQuestionTypeFirstCidDesc'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'question_desc' => 'getQuestionDesc',
        'question_video_image' => 'getQuestionVideoImage',
        'question_type_second_cid' => 'getQuestionTypeSecondCid',
        'question_video' => 'getQuestionVideo',
        'question_type_second_cid_desc' => 'getQuestionTypeSecondCidDesc',
        'question_pic' => 'getQuestionPic',
        'question_type_first_cid' => 'getQuestionTypeFirstCid',
        'question_type_first_cid_desc' => 'getQuestionTypeFirstCidDesc'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('question_desc', $data ?? [], null);
        $this->setIfExists('question_video_image', $data ?? [], null);
        $this->setIfExists('question_type_second_cid', $data ?? [], null);
        $this->setIfExists('question_video', $data ?? [], null);
        $this->setIfExists('question_type_second_cid_desc', $data ?? [], null);
        $this->setIfExists('question_pic', $data ?? [], null);
        $this->setIfExists('question_type_first_cid', $data ?? [], null);
        $this->setIfExists('question_type_first_cid_desc', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets question_desc
     *
     * @return string|null
     */
    public function getQuestionDesc()
    {
        return $this->container['question_desc'];
    }

    /**
     * Sets question_desc
     *
     * @param string|null $question_desc question_desc
     *
     * @return self
     */
    public function setQuestionDesc($question_desc)
    {
        if (is_null($question_desc)) {
            array_push($this->openAPINullablesSetToNull, 'question_desc');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('question_desc', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['question_desc'] = $question_desc;

        return $this;
    }

    /**
     * Gets question_video_image
     *
     * @return string|null
     */
    public function getQuestionVideoImage()
    {
        return $this->container['question_video_image'];
    }

    /**
     * Sets question_video_image
     *
     * @param string|null $question_video_image question_video_image
     *
     * @return self
     */
    public function setQuestionVideoImage($question_video_image)
    {
        if (is_null($question_video_image)) {
            array_push($this->openAPINullablesSetToNull, 'question_video_image');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('question_video_image', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['question_video_image'] = $question_video_image;

        return $this;
    }

    /**
     * Gets question_type_second_cid
     *
     * @return int|null
     */
    public function getQuestionTypeSecondCid()
    {
        return $this->container['question_type_second_cid'];
    }

    /**
     * Sets question_type_second_cid
     *
     * @param int|null $question_type_second_cid question_type_second_cid
     *
     * @return self
     */
    public function setQuestionTypeSecondCid($question_type_second_cid)
    {
        if (is_null($question_type_second_cid)) {
            array_push($this->openAPINullablesSetToNull, 'question_type_second_cid');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('question_type_second_cid', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['question_type_second_cid'] = $question_type_second_cid;

        return $this;
    }

    /**
     * Gets question_video
     *
     * @return string|null
     */
    public function getQuestionVideo()
    {
        return $this->container['question_video'];
    }

    /**
     * Sets question_video
     *
     * @param string|null $question_video question_video
     *
     * @return self
     */
    public function setQuestionVideo($question_video)
    {
        if (is_null($question_video)) {
            array_push($this->openAPINullablesSetToNull, 'question_video');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('question_video', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['question_video'] = $question_video;

        return $this;
    }

    /**
     * Gets question_type_second_cid_desc
     *
     * @return string|null
     */
    public function getQuestionTypeSecondCidDesc()
    {
        return $this->container['question_type_second_cid_desc'];
    }

    /**
     * Sets question_type_second_cid_desc
     *
     * @param string|null $question_type_second_cid_desc question_type_second_cid_desc
     *
     * @return self
     */
    public function setQuestionTypeSecondCidDesc($question_type_second_cid_desc)
    {
        if (is_null($question_type_second_cid_desc)) {
            array_push($this->openAPINullablesSetToNull, 'question_type_second_cid_desc');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('question_type_second_cid_desc', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['question_type_second_cid_desc'] = $question_type_second_cid_desc;

        return $this;
    }

    /**
     * Gets question_pic
     *
     * @return string|null
     */
    public function getQuestionPic()
    {
        return $this->container['question_pic'];
    }

    /**
     * Sets question_pic
     *
     * @param string|null $question_pic question_pic
     *
     * @return self
     */
    public function setQuestionPic($question_pic)
    {
        if (is_null($question_pic)) {
            array_push($this->openAPINullablesSetToNull, 'question_pic');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('question_pic', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['question_pic'] = $question_pic;

        return $this;
    }

    /**
     * Gets question_type_first_cid
     *
     * @return int|null
     */
    public function getQuestionTypeFirstCid()
    {
        return $this->container['question_type_first_cid'];
    }

    /**
     * Sets question_type_first_cid
     *
     * @param int|null $question_type_first_cid question_type_first_cid
     *
     * @return self
     */
    public function setQuestionTypeFirstCid($question_type_first_cid)
    {
        if (is_null($question_type_first_cid)) {
            array_push($this->openAPINullablesSetToNull, 'question_type_first_cid');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('question_type_first_cid', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['question_type_first_cid'] = $question_type_first_cid;

        return $this;
    }

    /**
     * Gets question_type_first_cid_desc
     *
     * @return string|null
     */
    public function getQuestionTypeFirstCidDesc()
    {
        return $this->container['question_type_first_cid_desc'];
    }

    /**
     * Sets question_type_first_cid_desc
     *
     * @param string|null $question_type_first_cid_desc question_type_first_cid_desc
     *
     * @return self
     */
    public function setQuestionTypeFirstCidDesc($question_type_first_cid_desc)
    {
        if (is_null($question_type_first_cid_desc)) {
            array_push($this->openAPINullablesSetToNull, 'question_type_first_cid_desc');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('question_type_first_cid_desc', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['question_type_first_cid_desc'] = $question_type_first_cid_desc;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


