<?php
/**
 * AfsOrdersProcessInfoDTO
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  com\jd\openapi\apiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */


/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace com\jd\openapi\apiClient\sp\aftercare\v0\model;

use \ArrayAccess;
use \com\jd\openapi\apiClient\ObjectSerializer;

/**
 * AfsOrdersProcessInfoDTO Class Doc Comment
 *
 * @category Class
 * @package  com\jd\openapi\apiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AfsOrdersProcessInfoDTO implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AfsOrdersProcessInfoDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'process_result_desc' => 'string',
        'xid_seller' => 'string',
        'process_name' => 'string',
        'process_result' => 'int',
        'process_notes' => 'string',
        'process_xid' => 'string',
        'processed_time' => 'int',
        'process_pin' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'process_result_desc' => null,
        'xid_seller' => null,
        'process_name' => null,
        'process_result' => 'int32',
        'process_notes' => null,
        'process_xid' => null,
        'processed_time' => 'int64',
        'process_pin' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'process_result_desc' => true,
		'xid_seller' => true,
		'process_name' => true,
		'process_result' => true,
		'process_notes' => true,
		'process_xid' => true,
		'processed_time' => true,
		'process_pin' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'process_result_desc' => 'processResultDesc',
        'xid_seller' => 'xidSeller',
        'process_name' => 'processName',
        'process_result' => 'processResult',
        'process_notes' => 'processNotes',
        'process_xid' => 'processXid',
        'processed_time' => 'processedTime',
        'process_pin' => 'processPin'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'process_result_desc' => 'setProcessResultDesc',
        'xid_seller' => 'setXidSeller',
        'process_name' => 'setProcessName',
        'process_result' => 'setProcessResult',
        'process_notes' => 'setProcessNotes',
        'process_xid' => 'setProcessXid',
        'processed_time' => 'setProcessedTime',
        'process_pin' => 'setProcessPin'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'process_result_desc' => 'getProcessResultDesc',
        'xid_seller' => 'getXidSeller',
        'process_name' => 'getProcessName',
        'process_result' => 'getProcessResult',
        'process_notes' => 'getProcessNotes',
        'process_xid' => 'getProcessXid',
        'processed_time' => 'getProcessedTime',
        'process_pin' => 'getProcessPin'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('process_result_desc', $data ?? [], null);
        $this->setIfExists('xid_seller', $data ?? [], null);
        $this->setIfExists('process_name', $data ?? [], null);
        $this->setIfExists('process_result', $data ?? [], null);
        $this->setIfExists('process_notes', $data ?? [], null);
        $this->setIfExists('process_xid', $data ?? [], null);
        $this->setIfExists('processed_time', $data ?? [], null);
        $this->setIfExists('process_pin', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets process_result_desc
     *
     * @return string|null
     */
    public function getProcessResultDesc()
    {
        return $this->container['process_result_desc'];
    }

    /**
     * Sets process_result_desc
     *
     * @param string|null $process_result_desc process_result_desc
     *
     * @return self
     */
    public function setProcessResultDesc($process_result_desc)
    {
        if (is_null($process_result_desc)) {
            array_push($this->openAPINullablesSetToNull, 'process_result_desc');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('process_result_desc', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['process_result_desc'] = $process_result_desc;

        return $this;
    }

    /**
     * Gets xid_seller
     *
     * @return string|null
     */
    public function getXidSeller()
    {
        return $this->container['xid_seller'];
    }

    /**
     * Sets xid_seller
     *
     * @param string|null $xid_seller xid_seller
     *
     * @return self
     */
    public function setXidSeller($xid_seller)
    {
        if (is_null($xid_seller)) {
            array_push($this->openAPINullablesSetToNull, 'xid_seller');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('xid_seller', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['xid_seller'] = $xid_seller;

        return $this;
    }

    /**
     * Gets process_name
     *
     * @return string|null
     */
    public function getProcessName()
    {
        return $this->container['process_name'];
    }

    /**
     * Sets process_name
     *
     * @param string|null $process_name process_name
     *
     * @return self
     */
    public function setProcessName($process_name)
    {
        if (is_null($process_name)) {
            array_push($this->openAPINullablesSetToNull, 'process_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('process_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['process_name'] = $process_name;

        return $this;
    }

    /**
     * Gets process_result
     *
     * @return int|null
     */
    public function getProcessResult()
    {
        return $this->container['process_result'];
    }

    /**
     * Sets process_result
     *
     * @param int|null $process_result process_result
     *
     * @return self
     */
    public function setProcessResult($process_result)
    {
        if (is_null($process_result)) {
            array_push($this->openAPINullablesSetToNull, 'process_result');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('process_result', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['process_result'] = $process_result;

        return $this;
    }

    /**
     * Gets process_notes
     *
     * @return string|null
     */
    public function getProcessNotes()
    {
        return $this->container['process_notes'];
    }

    /**
     * Sets process_notes
     *
     * @param string|null $process_notes process_notes
     *
     * @return self
     */
    public function setProcessNotes($process_notes)
    {
        if (is_null($process_notes)) {
            array_push($this->openAPINullablesSetToNull, 'process_notes');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('process_notes', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['process_notes'] = $process_notes;

        return $this;
    }

    /**
     * Gets process_xid
     *
     * @return string|null
     */
    public function getProcessXid()
    {
        return $this->container['process_xid'];
    }

    /**
     * Sets process_xid
     *
     * @param string|null $process_xid process_xid
     *
     * @return self
     */
    public function setProcessXid($process_xid)
    {
        if (is_null($process_xid)) {
            array_push($this->openAPINullablesSetToNull, 'process_xid');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('process_xid', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['process_xid'] = $process_xid;

        return $this;
    }

    /**
     * Gets processed_time
     *
     * @return int|null
     */
    public function getProcessedTime()
    {
        return $this->container['processed_time'];
    }

    /**
     * Sets processed_time
     *
     * @param int|null $processed_time processed_time
     *
     * @return self
     */
    public function setProcessedTime($processed_time)
    {
        if (is_null($processed_time)) {
            array_push($this->openAPINullablesSetToNull, 'processed_time');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('processed_time', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['processed_time'] = $processed_time;

        return $this;
    }

    /**
     * Gets process_pin
     *
     * @return string|null
     */
    public function getProcessPin()
    {
        return $this->container['process_pin'];
    }

    /**
     * Sets process_pin
     *
     * @param string|null $process_pin process_pin
     *
     * @return self
     */
    public function setProcessPin($process_pin)
    {
        if (is_null($process_pin)) {
            array_push($this->openAPINullablesSetToNull, 'process_pin');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('process_pin', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['process_pin'] = $process_pin;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


