<?php
/**
 * AfsOrdersConfirmReceiveInfoDTO
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  com\jd\openapi\apiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */


/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace com\jd\openapi\apiClient\sp\aftercare\v0\model;

use \ArrayAccess;
use \com\jd\openapi\apiClient\ObjectSerializer;

/**
 * AfsOrdersConfirmReceiveInfoDTO Class Doc Comment
 *
 * @category Class
 * @package  com\jd\openapi\apiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AfsOrdersConfirmReceiveInfoDTO implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AfsOrdersConfirmReceiveInfoDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'part_quality' => 'int',
        'part_appearance' => 'int',
        'part_packing' => 'int',
        'receiver_xid' => 'string',
        'receiver_pin' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'part_quality' => 'int32',
        'part_appearance' => 'int32',
        'part_packing' => 'int32',
        'receiver_xid' => null,
        'receiver_pin' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'part_quality' => true,
		'part_appearance' => true,
		'part_packing' => true,
		'receiver_xid' => true,
		'receiver_pin' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'part_quality' => 'partQuality',
        'part_appearance' => 'partAppearance',
        'part_packing' => 'partPacking',
        'receiver_xid' => 'receiverXid',
        'receiver_pin' => 'receiverPin'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'part_quality' => 'setPartQuality',
        'part_appearance' => 'setPartAppearance',
        'part_packing' => 'setPartPacking',
        'receiver_xid' => 'setReceiverXid',
        'receiver_pin' => 'setReceiverPin'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'part_quality' => 'getPartQuality',
        'part_appearance' => 'getPartAppearance',
        'part_packing' => 'getPartPacking',
        'receiver_xid' => 'getReceiverXid',
        'receiver_pin' => 'getReceiverPin'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('part_quality', $data ?? [], null);
        $this->setIfExists('part_appearance', $data ?? [], null);
        $this->setIfExists('part_packing', $data ?? [], null);
        $this->setIfExists('receiver_xid', $data ?? [], null);
        $this->setIfExists('receiver_pin', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets part_quality
     *
     * @return int|null
     */
    public function getPartQuality()
    {
        return $this->container['part_quality'];
    }

    /**
     * Sets part_quality
     *
     * @param int|null $part_quality part_quality
     *
     * @return self
     */
    public function setPartQuality($part_quality)
    {
        if (is_null($part_quality)) {
            array_push($this->openAPINullablesSetToNull, 'part_quality');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('part_quality', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['part_quality'] = $part_quality;

        return $this;
    }

    /**
     * Gets part_appearance
     *
     * @return int|null
     */
    public function getPartAppearance()
    {
        return $this->container['part_appearance'];
    }

    /**
     * Sets part_appearance
     *
     * @param int|null $part_appearance part_appearance
     *
     * @return self
     */
    public function setPartAppearance($part_appearance)
    {
        if (is_null($part_appearance)) {
            array_push($this->openAPINullablesSetToNull, 'part_appearance');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('part_appearance', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['part_appearance'] = $part_appearance;

        return $this;
    }

    /**
     * Gets part_packing
     *
     * @return int|null
     */
    public function getPartPacking()
    {
        return $this->container['part_packing'];
    }

    /**
     * Sets part_packing
     *
     * @param int|null $part_packing part_packing
     *
     * @return self
     */
    public function setPartPacking($part_packing)
    {
        if (is_null($part_packing)) {
            array_push($this->openAPINullablesSetToNull, 'part_packing');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('part_packing', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['part_packing'] = $part_packing;

        return $this;
    }

    /**
     * Gets receiver_xid
     *
     * @return string|null
     */
    public function getReceiverXid()
    {
        return $this->container['receiver_xid'];
    }

    /**
     * Sets receiver_xid
     *
     * @param string|null $receiver_xid receiver_xid
     *
     * @return self
     */
    public function setReceiverXid($receiver_xid)
    {
        if (is_null($receiver_xid)) {
            array_push($this->openAPINullablesSetToNull, 'receiver_xid');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('receiver_xid', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['receiver_xid'] = $receiver_xid;

        return $this;
    }

    /**
     * Gets receiver_pin
     *
     * @return string|null
     */
    public function getReceiverPin()
    {
        return $this->container['receiver_pin'];
    }

    /**
     * Sets receiver_pin
     *
     * @param string|null $receiver_pin receiver_pin
     *
     * @return self
     */
    public function setReceiverPin($receiver_pin)
    {
        if (is_null($receiver_pin)) {
            array_push($this->openAPINullablesSetToNull, 'receiver_pin');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('receiver_pin', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['receiver_pin'] = $receiver_pin;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


