<?php
/**
 * OrdersVerificationCodesVerificationCodeBaseDTO
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  com\jd\openapi\apiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */


/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace com\jd\openapi\apiClient\sp\order\v0\model;

use \ArrayAccess;
use \com\jd\openapi\apiClient\ObjectSerializer;

/**
 * OrdersVerificationCodesVerificationCodeBaseDTO Class Doc Comment
 *
 * @category Class
 * @package  com\jd\openapi\apiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class OrdersVerificationCodesVerificationCodeBaseDTO implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'OrdersVerificationCodesVerificationCodeBaseDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'expiry_start_time' => 'int',
        'status_modified_time' => 'int',
        'consumed_time' => 'int',
        'send_count' => 'int',
        'expiry_end_time' => 'int',
        'card_number' => 'string',
        'status' => 'int',
        'pwd_number' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'expiry_start_time' => 'int64',
        'status_modified_time' => 'int64',
        'consumed_time' => 'int64',
        'send_count' => 'int32',
        'expiry_end_time' => 'int64',
        'card_number' => null,
        'status' => 'int32',
        'pwd_number' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'expiry_start_time' => true,
		'status_modified_time' => true,
		'consumed_time' => true,
		'send_count' => true,
		'expiry_end_time' => true,
		'card_number' => true,
		'status' => true,
		'pwd_number' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'expiry_start_time' => 'expiryStartTime',
        'status_modified_time' => 'statusModifiedTime',
        'consumed_time' => 'consumedTime',
        'send_count' => 'sendCount',
        'expiry_end_time' => 'expiryEndTime',
        'card_number' => 'cardNumber',
        'status' => 'status',
        'pwd_number' => 'pwdNumber'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'expiry_start_time' => 'setExpiryStartTime',
        'status_modified_time' => 'setStatusModifiedTime',
        'consumed_time' => 'setConsumedTime',
        'send_count' => 'setSendCount',
        'expiry_end_time' => 'setExpiryEndTime',
        'card_number' => 'setCardNumber',
        'status' => 'setStatus',
        'pwd_number' => 'setPwdNumber'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'expiry_start_time' => 'getExpiryStartTime',
        'status_modified_time' => 'getStatusModifiedTime',
        'consumed_time' => 'getConsumedTime',
        'send_count' => 'getSendCount',
        'expiry_end_time' => 'getExpiryEndTime',
        'card_number' => 'getCardNumber',
        'status' => 'getStatus',
        'pwd_number' => 'getPwdNumber'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('expiry_start_time', $data ?? [], null);
        $this->setIfExists('status_modified_time', $data ?? [], null);
        $this->setIfExists('consumed_time', $data ?? [], null);
        $this->setIfExists('send_count', $data ?? [], null);
        $this->setIfExists('expiry_end_time', $data ?? [], null);
        $this->setIfExists('card_number', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('pwd_number', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets expiry_start_time
     *
     * @return int|null
     */
    public function getExpiryStartTime()
    {
        return $this->container['expiry_start_time'];
    }

    /**
     * Sets expiry_start_time
     *
     * @param int|null $expiry_start_time expiry_start_time
     *
     * @return self
     */
    public function setExpiryStartTime($expiry_start_time)
    {
        if (is_null($expiry_start_time)) {
            array_push($this->openAPINullablesSetToNull, 'expiry_start_time');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('expiry_start_time', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['expiry_start_time'] = $expiry_start_time;

        return $this;
    }

    /**
     * Gets status_modified_time
     *
     * @return int|null
     */
    public function getStatusModifiedTime()
    {
        return $this->container['status_modified_time'];
    }

    /**
     * Sets status_modified_time
     *
     * @param int|null $status_modified_time status_modified_time
     *
     * @return self
     */
    public function setStatusModifiedTime($status_modified_time)
    {
        if (is_null($status_modified_time)) {
            array_push($this->openAPINullablesSetToNull, 'status_modified_time');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('status_modified_time', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['status_modified_time'] = $status_modified_time;

        return $this;
    }

    /**
     * Gets consumed_time
     *
     * @return int|null
     */
    public function getConsumedTime()
    {
        return $this->container['consumed_time'];
    }

    /**
     * Sets consumed_time
     *
     * @param int|null $consumed_time consumed_time
     *
     * @return self
     */
    public function setConsumedTime($consumed_time)
    {
        if (is_null($consumed_time)) {
            array_push($this->openAPINullablesSetToNull, 'consumed_time');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('consumed_time', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['consumed_time'] = $consumed_time;

        return $this;
    }

    /**
     * Gets send_count
     *
     * @return int|null
     */
    public function getSendCount()
    {
        return $this->container['send_count'];
    }

    /**
     * Sets send_count
     *
     * @param int|null $send_count send_count
     *
     * @return self
     */
    public function setSendCount($send_count)
    {
        if (is_null($send_count)) {
            array_push($this->openAPINullablesSetToNull, 'send_count');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('send_count', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['send_count'] = $send_count;

        return $this;
    }

    /**
     * Gets expiry_end_time
     *
     * @return int|null
     */
    public function getExpiryEndTime()
    {
        return $this->container['expiry_end_time'];
    }

    /**
     * Sets expiry_end_time
     *
     * @param int|null $expiry_end_time expiry_end_time
     *
     * @return self
     */
    public function setExpiryEndTime($expiry_end_time)
    {
        if (is_null($expiry_end_time)) {
            array_push($this->openAPINullablesSetToNull, 'expiry_end_time');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('expiry_end_time', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['expiry_end_time'] = $expiry_end_time;

        return $this;
    }

    /**
     * Gets card_number
     *
     * @return string|null
     */
    public function getCardNumber()
    {
        return $this->container['card_number'];
    }

    /**
     * Sets card_number
     *
     * @param string|null $card_number card_number
     *
     * @return self
     */
    public function setCardNumber($card_number)
    {
        if (is_null($card_number)) {
            array_push($this->openAPINullablesSetToNull, 'card_number');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('card_number', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['card_number'] = $card_number;

        return $this;
    }

    /**
     * Gets status
     *
     * @return int|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param int|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            array_push($this->openAPINullablesSetToNull, 'status');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('status', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets pwd_number
     *
     * @return string|null
     */
    public function getPwdNumber()
    {
        return $this->container['pwd_number'];
    }

    /**
     * Sets pwd_number
     *
     * @param string|null $pwd_number pwd_number
     *
     * @return self
     */
    public function setPwdNumber($pwd_number)
    {
        if (is_null($pwd_number)) {
            array_push($this->openAPINullablesSetToNull, 'pwd_number');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('pwd_number', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['pwd_number'] = $pwd_number;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


